package techniqueparity_test

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/config"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/engine"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/market"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/replaycapture"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/strategyutil"
)

// The golden is the decision of the frozen Python technique publishers
// (technique_detectors.py) over the committed closed-bar captures, generated by
// generate_oracle_golden.py. The Go publishers must agree bar by bar on
// presence, direction, entry band and confluence stars: none may fire where the
// oracle did not, none may stay silent where it did.

// knownDivergences are the only bars where Go deliberately differs from the
// oracle, each with its reason. A divergence not listed here fails the test, and
// a listed one that stops occurring fails it too, so the list cannot rot.
//
// The frozen publishers call _zone_grabs_for(st, zone, direction) without its
// pip_size argument, so the sweep grab that confirms a zone is matched with a
// hard-coded 0.1 pip tolerance on every instrument. That is XAU's real pip, so
// XAU is exact, but on a 0.01-pip pair it is ten times too wide: a liquidity
// sweep 7 pips below this USDJPY FVG+iFVG band "confirmed" it in Python. Go uses
// the instrument's own pip size and so does not trade that bar.
var knownDivergences = map[string]string{
	"USDJPY confluence_zone_reaction bar 1790888700": "oracle matches the sweep grab with a hard-coded 0.1 pip tolerance",
}

const frozenCommit = "1c9f32303b7e9f15fc8e3767b5045ac1e8a37adc"

// detectors maps each frozen publisher to the Go technique it corresponds to.
var detectors = map[string]string{
	"supply_demand_technique_reaction": strategyutil.TechniqueSupplyDemand,
	"order_block_technique_reaction":   strategyutil.TechniqueOrderBlock,
	"fvg_technique_reaction":           strategyutil.TechniqueFVG,
	"ifvg_technique_reaction":          strategyutil.TechniqueIFVG,
	"crt_technique_reaction":           strategyutil.TechniqueCRT,
	"confluence_zone_reaction":         "confluence_zone",
}

type goldenDecision struct {
	Direction  string  `json:"direction"`
	EntryLow   float64 `json:"entry_low"`
	EntryHigh  float64 `json:"entry_high"`
	Confluence int     `json:"confluence"`
}

type goldenSymbol struct {
	Capture  string `json:"capture"`
	FirstBar int64  `json:"first_bar"`
	LastBar  int64  `json:"last_bar"`
	Bars     []struct {
		Bar       int64                     `json:"bar"`
		Detectors map[string]goldenDecision `json:"detectors"`
	} `json:"bars"`
}

type golden struct {
	OracleCommit string                  `json:"oracle_commit"`
	Symbols      map[string]goldenSymbol `json:"symbols"`
}

type decision struct {
	direction  string
	low, high  float64
	confluence int
}

// observe replays the capture and returns every technique publisher's decision
// per closed M5 bar.
// debugBars, from TECHNIQUE_DEBUG_BARS (comma-separated bar times), logs the
// instances and bands the Go publishers saw on those bars, for diagnosing a
// disagreement with the oracle.
var debugBars = func() map[int64]bool {
	out := map[int64]bool{}
	for _, field := range strings.Split(os.Getenv("TECHNIQUE_DEBUG_BARS"), ",") {
		if v, err := strconv.ParseInt(field, 10, 64); err == nil {
			out[v] = true
		}
	}
	return out
}()

func observe(t *testing.T, doc *config.Document, symbol, capture string) (map[int64]map[string]decision, float64) {
	t.Helper()
	settings, err := engine.LoadSettings(doc, market.M5, false)
	if err != nil {
		t.Fatal(err)
	}
	if err := engine.ApplyInstrument(&settings, doc, symbol); err != nil {
		t.Fatal(err)
	}
	var legacy strategyutil.LegacyDetectorSettings
	found := false
	for _, cfg := range settings.Strategies {
		if cfg.ID == "break_retest" {
			if legacy, err = strategyutil.ParseLegacyDetectorSettings(cfg.Parameters); err != nil {
				t.Fatal(err)
			}
			found = true
		}
	}
	if !found {
		t.Fatal("no detector-contract strategy carries the legacy detector settings")
	}
	loaded, err := replaycapture.Load(filepath.Join("..", "..", "testdata", capture))
	if err != nil {
		t.Fatal(err)
	}
	got := map[int64]map[string]decision{}
	_, err = replaycapture.Replay(doc, loaded, market.M5, replaycapture.Options{OnEvaluation: func(e engine.Evaluation) {
		if e.Timeframe != market.M5 {
			return
		}
		source, ok := strategyutil.NewTechniqueSource(e.Context, market.M5, legacy)
		if !ok {
			return
		}
		if debugBars[e.BarTime] {
			t.Logf("BAR %d price %.5f atr %.5f n %d", e.BarTime, source.Detector.Price, source.Detector.ATR, len(source.Detector.Frame.Bars))
			for _, in := range source.Instances {
				t.Logf("  inst %s %s %.5f-%.5f origin %d touches %d mit %v score %.1f clipped %v", in.Technique, in.Side, in.Low, in.High, in.OriginIndex, in.Touches, in.Mitigated, in.ZoneScore, in.EntryClipped)
			}
			for _, b := range source.Bands() {
				t.Logf("  band %s %.5f-%.5f %v %.1f", b.Side, b.Low, b.High, b.Tags, b.Score)
			}
		}
		out := map[string]decision{}
		for name, technique := range detectors {
			var d *strategyutil.TechniqueDecision
			if technique == "confluence_zone" {
				d = source.ConfluenceZone()
			} else {
				d = source.Technique(technique)
			}
			if d != nil {
				out[name] = decision{string(d.Direction), d.EntryLow(), d.EntryHigh(), d.Result.Stars}
			}
		}
		got[e.BarTime] = out
	}})
	if err != nil {
		t.Fatal(err)
	}
	return got, settings.Geometry.PipSize
}

func TestTechniquePublishersMatchTheFrozenPythonOracleBarByBar(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "testdata", "technique-parity-oracle.json"))
	if err != nil {
		t.Fatal(err)
	}
	var g golden
	if err := json.Unmarshal(data, &g); err != nil {
		t.Fatal(err)
	}
	if g.OracleCommit != frozenCommit {
		t.Fatalf("golden was not generated from the frozen oracle: %q", g.OracleCommit)
	}
	doc, err := config.ResolveDocument(filepath.Join("..", "..", "..", "config", "apexvoid.yml"))
	if err != nil {
		t.Fatal(err)
	}
	var symbols []string
	for symbol := range g.Symbols {
		symbols = append(symbols, symbol)
	}
	sort.Strings(symbols)
	var names []string
	for name := range detectors {
		names = append(names, name)
	}
	sort.Strings(names)
	compared := map[string]int{}
	seenDivergence := map[string]bool{}
	for _, symbol := range symbols {
		want := g.Symbols[symbol]
		got, pip := observe(t, doc, symbol, want.Capture)
		tolerance := pip * .01
		expected := map[int64]map[string]goldenDecision{}
		for _, bar := range want.Bars {
			expected[bar.Bar] = bar.Detectors
		}
		var mismatches []string
		for bar := range got {
			if bar < want.FirstBar || bar > want.LastBar {
				delete(got, bar)
			}
		}
		barSet := map[int64]bool{}
		for bar := range got {
			barSet[bar] = true
		}
		for bar := range expected {
			barSet[bar] = true
		}
		var bars []int64
		for bar := range barSet {
			bars = append(bars, bar)
		}
		sort.Slice(bars, func(i, j int) bool { return bars[i] < bars[j] })
		for _, bar := range bars {
			for _, name := range names {
				oracle, wantFire := expected[bar][name]
				have, haveFire := got[bar][name]
				switch {
				case wantFire && !haveFire:
					mismatches = append(mismatches, fmt.Sprintf("%s %s bar %d: oracle %s, Go silent", symbol, name, bar, oracle.Direction))
				case !wantFire && haveFire:
					mismatches = append(mismatches, fmt.Sprintf("%s %s bar %d: Go %s, oracle silent", symbol, name, bar, have.direction))
				case wantFire:
					compared[name]++
					if have.direction != oracle.Direction {
						mismatches = append(mismatches, fmt.Sprintf("%s %s bar %d: direction %s, oracle %s", symbol, name, bar, have.direction, oracle.Direction))
						continue
					}
					if math.Abs(have.low-oracle.EntryLow) > tolerance || math.Abs(have.high-oracle.EntryHigh) > tolerance {
						mismatches = append(mismatches, fmt.Sprintf("%s %s bar %d: entry %.6f-%.6f, oracle %.6f-%.6f", symbol, name, bar, have.low, have.high, oracle.EntryLow, oracle.EntryHigh))
					}
					if have.confluence != oracle.Confluence {
						mismatches = append(mismatches, fmt.Sprintf("%s %s bar %d: confluence %d, oracle %d", symbol, name, bar, have.confluence, oracle.Confluence))
					}
				}
			}
		}
		for i, m := range mismatches {
			if reason, known := knownDivergences[divergenceKey(m)]; known {
				seenDivergence[divergenceKey(m)] = true
				t.Logf("known divergence: %s (%s)", m, reason)
				continue
			}
			if i == 15 {
				t.Errorf("%s: ... and %d more", symbol, len(mismatches)-15)
				break
			}
			t.Error(m)
		}
	}
	for key := range knownDivergences {
		if !seenDivergence[key] {
			t.Errorf("known divergence %q no longer occurs: remove it from knownDivergences", key)
		}
	}
	// The comparison is only meaningful if the oracle decided something for each
	// publisher on these captures.
	for _, name := range names {
		if compared[name] == 0 {
			t.Errorf("the golden holds no %s decision to compare", name)
		}
	}
	t.Logf("compared decisions: %v", compared)
}

// divergenceKey reduces a mismatch message to "<symbol> <publisher> bar <n>".
func divergenceKey(message string) string {
	fields := strings.Fields(message)
	if len(fields) < 4 {
		return message
	}
	return strings.TrimSuffix(strings.Join(fields[:4], " "), ":")
}
