// Package keylevelparity_test proves Key Level against the Python detector
// that ran during the profitable XAU week (14–18 Sep 2026: +567 pips, 6W/3L).
// The golden is that detector's decision (key_level_reaction at commit
// a1c77584, the end of that week) on every closed M5 bar of the committed real
// XAU, GBPUSD and USDJPY captures, generated by running the Python
// implementation (generate_oracle_golden.py) and never by Go. This test replays
// the same captures through the Go engine and requires, bar by bar, the same
// decision: the same level and role, direction, entry band, confluence stars,
// reaction type and touch/confirmation bars — and silence where Python was
// silent.
package keylevelparity_test

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/config"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/engine"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/market"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/opportunity"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/replaycapture"
)

type decision struct {
	Direction       string  `json:"direction"`
	EntryLow        float64 `json:"entry_low"`
	EntryHigh       float64 `json:"entry_high"`
	Confluence      int     `json:"confluence"`
	KeyLevel        float64 `json:"key_level"`
	StructuralKind  string  `json:"structural_kind"`
	ConfirmationTyp string  `json:"confirmation_type"`
	TouchBar        *int64  `json:"touch_bar"`
	ConfirmationBar *int64  `json:"confirmation_bar"`
	SourceTouches   int     `json:"source_touches"`
	Role            string  `json:"role"`
}

type symbolGolden struct {
	Capture   string              `json:"capture"`
	Bars      []int64             `json:"bars"`
	Decisions map[string]decision `json:"decisions"`
}

type golden struct {
	OracleCommit string                  `json:"oracle_commit"`
	Symbols      map[string]symbolGolden `json:"symbols"`
}

func load(t *testing.T) golden {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "testdata", "key-level-oracle.json"))
	if err != nil {
		t.Fatal(err)
	}
	var g golden
	if err := json.Unmarshal(data, &g); err != nil {
		t.Fatal(err)
	}
	return g
}

func TestKeyLevelMatchesTheProfitableWeekPython(t *testing.T) {
	g := load(t)
	doc, err := config.ResolveDocument(filepath.Join("..", "..", "..", "config", "apexvoid.yml"))
	if err != nil {
		t.Fatal(err)
	}
	totalDecisions, totalMatched := 0, 0
	for symbol, want := range g.Symbols {
		capture, err := replaycapture.Load(filepath.Join("..", "..", "testdata", want.Capture))
		if err != nil {
			t.Fatal(err)
		}
		digits := 2
		if capture.Symbol != "XAU" && capture.Symbol != "USDJPY" {
			digits = 5
		} else if capture.Symbol == "USDJPY" {
			digits = 3
		}
		tick := math.Pow10(-digits)
		got := map[int64][]opportunity.Candidate{}
		_, err = replaycapture.Replay(doc, capture, market.M5, replaycapture.Options{OnEvaluation: func(e engine.Evaluation) {
			if e.Timeframe != market.M5 {
				return
			}
			for _, c := range e.Candidates {
				if c.Strategy == "key_level" {
					got[e.BarTime] = append(got[e.BarTime], c)
				}
			}
		}})
		if err != nil {
			t.Fatal(err)
		}
		var failures []string
		for _, bar := range want.Bars {
			expected, hasExpected := want.Decisions[fmt.Sprint(bar)]
			actual := got[bar]
			switch {
			case !hasExpected && len(actual) == 0:
			case !hasExpected:
				failures = append(failures, fmt.Sprintf("%s bar %d: Go emitted %s, Python was silent", symbol, bar, describe(actual[0])))
			case len(actual) != 1:
				failures = append(failures, fmt.Sprintf("%s bar %d: Python %s %.5f-%.5f level %.5f %s; Go emitted %d candidates", symbol, bar, expected.Direction, expected.EntryLow, expected.EntryHigh, expected.KeyLevel, expected.Role, len(actual)))
			default:
				totalDecisions++
				c := actual[0]
				touch, confirm := int64(0), int64(0)
				if c.Reaction != nil {
					touch, confirm = c.Reaction.TouchBarTime, c.Reaction.ConfirmationBarTime
				}
				stars := 0
				if c.DetectorConfluence != nil {
					stars = c.DetectorConfluence.SelectedStars
				}
				switch {
				case string(c.Direction) != expected.Direction:
					failures = append(failures, fmt.Sprintf("%s bar %d: direction Go %s, Python %s", symbol, bar, c.Direction, expected.Direction))
				case math.Abs(c.Entry.Low-expected.EntryLow) > tick+1e-9 || math.Abs(c.Entry.High-expected.EntryHigh) > tick+1e-9:
					failures = append(failures, fmt.Sprintf("%s bar %d: entry Go %.5f-%.5f, Python %.5f-%.5f", symbol, bar, c.Entry.Low, c.Entry.High, expected.EntryLow, expected.EntryHigh))
				case stars != expected.Confluence:
					failures = append(failures, fmt.Sprintf("%s bar %d: confluence Go %d, Python %d", symbol, bar, stars, expected.Confluence))
				case expected.TouchBar != nil && touch != *expected.TouchBar || expected.ConfirmationBar != nil && confirm != *expected.ConfirmationBar:
					failures = append(failures, fmt.Sprintf("%s bar %d: reaction bars Go %d/%d, Python %v/%v", symbol, bar, touch, confirm, expected.TouchBar, expected.ConfirmationBar))
				case c.Reaction == nil || c.Reaction.Pattern != expected.ConfirmationTyp:
					failures = append(failures, fmt.Sprintf("%s bar %d: reaction type differs from Python %s", symbol, bar, expected.ConfirmationTyp))
				default:
					totalMatched++
				}
			}
		}
		sort.Strings(failures)
		for i, f := range failures {
			if i >= 25 {
				t.Errorf("%s: ... and %d more", symbol, len(failures)-25)
				break
			}
			t.Error(f)
		}
		t.Logf("%s: %d bars, %d Python decisions, %d mismatches", symbol, len(want.Bars), len(want.Decisions), len(failures))
	}
	if totalDecisions < 100 {
		t.Fatalf("the golden exercises only %d decisions", totalDecisions)
	}
	_ = totalMatched
}

func describe(c opportunity.Candidate) string {
	return fmt.Sprintf("%s %.5f-%.5f", c.Direction, c.Entry.Low, c.Entry.High)
}
