package config_test

// Configuration V3 Stage C6: cross-language parity against the shared
// canonical fixture (contracts/configuration/examples/resolved-
// production-v3.json), generated by config/scripts/resolve_reference.py
// — a fourth, minimal reference implementation of §14 whose only job is
// producing this fixture and validating it against the JSON Schema. §38
// requires every real per-language V3 reader (this package's
// config.ResolveDocument, Python's app/configuration/v3_root.py, .NET's
// ctrader-engine/src/ConfigurationV3.cs) to reproduce this exact document
// when resolving the real config/apexvoid.yml for the production
// environment — not that they share code, but that independent
// implementations of one spec, run against the same input, converge on
// one answer. This file is Go's half of that proof; Python's is
// algo-bot/tests/test_config_v3_cross_language_fixture.py; .NET's is
// ConfigurationV3Tests.cs's ResolveDocumentMatchesCanonicalFixture.

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"

	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/config"
)

func fixturePath() string {
	return repoConfigPath("..", "contracts", "configuration", "examples", "resolved-production-v3.json")
}

// normalizeNumbers recursively converts every int (yaml.v3's decoding for
// a bare integer literal) to float64, matching what encoding/json always
// produces when unmarshaling a JSON number into `any` — without this, a
// value that's semantically identical (3 vs 3.0) would spuriously fail
// reflect.DeepEqual purely because yaml.v3 and encoding/json disagree on
// which Go numeric type represents "a whole number with no decimal
// point in the source." This mirrors why the Python parity test doesn't
// need an analogous step: Python's `3 == 3.0` is already True, so dict
// equality there tolerates the same distinction for free.
func normalizeNumbers(node any) any {
	switch v := node.(type) {
	case map[string]any:
		out := make(map[string]any, len(v))
		for key, value := range v {
			out[key] = normalizeNumbers(value)
		}
		return out
	case []any:
		out := make([]any, len(v))
		for i, value := range v {
			out[i] = normalizeNumbers(value)
		}
		return out
	case int:
		return float64(v)
	default:
		return v
	}
}

func TestResolveDocumentMatchesCanonicalFixture(t *testing.T) {
	doc, err := config.ResolveDocument(repoConfigPath("apexvoid.yml"))
	if err != nil {
		t.Fatalf("ResolveDocument: %v", err)
	}

	fixtureBytes, err := os.ReadFile(fixturePath())
	if err != nil {
		t.Fatalf("reading fixture: %v", err)
	}
	var fixture any
	if err := json.Unmarshal(fixtureBytes, &fixture); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}

	got := normalizeNumbers(doc.Raw())
	want := normalizeNumbers(fixture)

	if !reflect.DeepEqual(got, want) {
		t.Fatalf(
			"ResolveDocument(config/apexvoid.yml) no longer matches "+
				"contracts/configuration/examples/resolved-production-v3.json.\n"+
				"Either config/*.yml changed without regenerating the fixture "+
				"(algo-bot/.venv/bin/python config/scripts/resolve_reference.py "+
				"--environment production --write-fixture) or ResolveDocument's "+
				"resolution logic diverged from resolve_reference.py's — both must "+
				"implement §14 identically.\ngot:  %#v\nwant: %#v",
			got, want,
		)
	}
}

func TestFixtureDeclaresProductionEnvironment(t *testing.T) {
	fixtureBytes, err := os.ReadFile(fixturePath())
	if err != nil {
		t.Fatalf("reading fixture: %v", err)
	}
	var fixture map[string]any
	if err := json.Unmarshal(fixtureBytes, &fixture); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}
	runtime, _ := fixture["runtime"].(map[string]any)
	if runtime["environment"] != "production" {
		t.Fatalf("fixture runtime.environment = %v, want \"production\"", runtime["environment"])
	}
}
