package scalpbreakoutretest

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/market"
)

// episode-cases.json is generated by test/scalpparity/generate_unit_cases.py:
// hand-built bar sequences run through the Python Breakout Retest V2 state
// machine that ran in the profitable XAU week. Every Go state, failure reason
// and measured quantity must equal Python's.

type caseParams struct {
	CrossTolerance       float64 `json:"cross_tolerance"`
	BreakoutMargin       float64 `json:"breakout_margin"`
	MaxBreakDelayBars    *int    `json:"max_break_delay_bars"`
	AcceptanceBars       int     `json:"acceptance_bars"`
	AcceptanceRequired   int     `json:"acceptance_required_closes"`
	MinRetestDelayBars   int     `json:"min_retest_delay_bars"`
	MaxRetestDelayBars   int     `json:"max_retest_delay_bars"`
	RetestFrontRun       float64 `json:"retest_front_run_tolerance"`
	MaxRetestPenetration float64 `json:"max_retest_penetration"`
	ConfirmationMode     string  `json:"confirmation_mode"`
}

type caseExpect struct {
	State                   string   `json:"state"`
	FailureReason           *string  `json:"failure_reason"`
	BreakIndex              *int     `json:"break_index"`
	BreakDistance           *float64 `json:"break_distance"`
	BreakDistanceATR        *float64 `json:"break_distance_atr"`
	Accepted                *bool    `json:"accepted"`
	AcceptanceBars          *int     `json:"acceptance_bars"`
	RetestIndex             *int     `json:"retest_index"`
	BarsUntilRetest         *int     `json:"bars_until_retest"`
	RetestPenetrationATR    *float64 `json:"retest_penetration_atr"`
	ConfirmationType        *string  `json:"confirmation_type"`
	DirectionallyValidClose *bool    `json:"directionally_valid_close"`
}

type episodeCase struct {
	Name         string       `json:"name"`
	Side         string       `json:"side"`
	Level        float64      `json:"level"`
	ATR          float64      `json:"atr"`
	Bars         [][4]float64 `json:"bars"`
	SourceIndex  *int         `json:"source_index"`
	Invalidation *float64     `json:"invalidation"`
	Params       caseParams   `json:"params"`
	Expect       caseExpect   `json:"expect"`
}

func loadCases(t *testing.T) []episodeCase {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "episode-cases.json"))
	if err != nil {
		t.Fatal(err)
	}
	var doc struct {
		Cases []episodeCase `json:"cases"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatal(err)
	}
	return doc.Cases
}

func (c episodeCase) candles() []market.Candle {
	out := make([]market.Candle, len(c.Bars))
	for i, b := range c.Bars {
		out[i] = market.Candle{Time: 1_790_000_000 + 300*int64(i), Open: b[0], High: b[1], Low: b[2], Close: b[3], Volume: 1}
	}
	return out
}

func near(a, b *float64) bool {
	if a == nil || b == nil {
		return a == b
	}
	return math.Abs(*a-*b) < 1e-9
}

func TestEpisodeStateMachineMatchesPython(t *testing.T) {
	cases := loadCases(t)
	if len(cases) < 30 {
		t.Fatalf("only %d cases", len(cases))
	}
	armed := 0
	for _, tc := range cases {
		side := market.Buy
		if tc.Side == "SELL" {
			side = market.Sell
		}
		p := tc.Params
		got := evaluateEpisode(tc.candles(), levelCandidate{Level: tc.Level, Side: side, SourceIndex: tc.SourceIndex, Invalidation: tc.Invalidation}, episodeParams{
			ATR: tc.ATR, CrossTolerance: p.CrossTolerance, BreakoutMargin: p.BreakoutMargin, MaxBreakDelayBars: p.MaxBreakDelayBars,
			AcceptanceBars: p.AcceptanceBars, AcceptanceRequired: p.AcceptanceRequired, MinRetestDelayBars: p.MinRetestDelayBars,
			MaxRetestDelayBars: p.MaxRetestDelayBars, RetestFrontRun: p.RetestFrontRun, MaxRetestPenetration: p.MaxRetestPenetration,
			ConfirmationMode: p.ConfirmationMode,
		})
		want := tc.Expect
		fail := func(field string, g, w any) { t.Errorf("%s: %s = %v, Python %v", tc.Name, field, g, w) }
		if got.State != want.State {
			fail("state", got.State, want.State)
		}
		reason := ""
		if want.FailureReason != nil {
			reason = *want.FailureReason
		}
		if got.FailureReason != reason {
			fail("failure_reason", got.FailureReason, reason)
		}
		if want.BreakIndex != nil && got.BreakIndex != *want.BreakIndex || want.BreakIndex == nil && got.BreakIndex != -1 {
			fail("break_index", got.BreakIndex, want.BreakIndex)
		}
		if !near(got.BreakDistanceAT, want.BreakDistanceATR) {
			fail("break_distance_atr", got.BreakDistanceAT, want.BreakDistanceATR)
		}
		if want.Accepted != nil && got.Accepted != *want.Accepted {
			fail("accepted", got.Accepted, *want.Accepted)
		}
		if want.AcceptanceBars != nil && got.AcceptanceBars != *want.AcceptanceBars {
			fail("acceptance_bars", got.AcceptanceBars, *want.AcceptanceBars)
		}
		if want.RetestIndex != nil && got.RetestIndex != *want.RetestIndex || want.RetestIndex == nil && got.RetestIndex != -1 {
			fail("retest_index", got.RetestIndex, want.RetestIndex)
		}
		if (got.BarsUntilRetest == nil) != (want.BarsUntilRetest == nil) || got.BarsUntilRetest != nil && *got.BarsUntilRetest != *want.BarsUntilRetest {
			fail("bars_until_retest", got.BarsUntilRetest, want.BarsUntilRetest)
		}
		if !near(got.RetestPenATR, want.RetestPenetrationATR) {
			fail("retest_penetration_atr", got.RetestPenATR, want.RetestPenetrationATR)
		}
		confirmation := ""
		if want.ConfirmationType != nil {
			confirmation = *want.ConfirmationType
		}
		if got.ConfirmationType != confirmation {
			fail("confirmation_type", got.ConfirmationType, confirmation)
		}
		if want.DirectionallyValidClose != nil && got.DirectionallyValidClose != *want.DirectionallyValidClose {
			fail("directionally_valid_close", got.DirectionallyValidClose, *want.DirectionallyValidClose)
		}
		if got.State == stateArmed {
			armed++
		}
	}
	if armed < 6 {
		t.Fatalf("only %d armed cases: the golden no longer exercises the armed path", armed)
	}
}
