package scalpbreakoutretest

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/market"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/strategyutil"
)

// source-cases.json is generated by test/scalpparity/generate_source_cases.py:
// seeded random-walk M5 series through the Python Breakout Retest V2 level
// sources of the profitable XAU week. The Go builders must produce the same
// micro structure, level candidates and compression box.

type sourceCandidate struct {
	Level       float64 `json:"level"`
	Source      string  `json:"source"`
	Subtype     string  `json:"subtype"`
	Timeframe   string  `json:"timeframe"`
	SourceIndex *int    `json:"source_index"`
}

type sourceCase struct {
	Seed       int          `json:"seed"`
	Bars       [][4]float64 `json:"bars"`
	ATR        float64      `json:"atr"`
	Swings     [][3]any     `json:"swings"`
	EqualHighs []float64    `json:"equal_highs"`
	EqualLows  []float64    `json:"equal_lows"`
	KeyLevels  [][2]float64 `json:"key_levels"`
	Price      float64      `json:"price"`
	Flip       map[string][]sourceCandidate
	Liquidity  map[string][]sourceCandidate
	M5         map[string][]sourceCandidate
	Box        *struct {
		Low      float64 `json:"box_low"`
		High     float64 `json:"box_high"`
		Bars     int     `json:"box_bars"`
		EndIndex int     `json:"box_end_index"`
		Touches  int     `json:"touch_count"`
		Detect   map[string]struct {
			State             string   `json:"state"`
			Level             *float64 `json:"level"`
			Close             *float64 `json:"close"`
			BreakDisplacement *float64 `json:"break_displacement"`
		} `json:"detect"`
	} `json:"box"`
}

func (c sourceCase) candles() []market.Candle {
	out := make([]market.Candle, len(c.Bars))
	for i, b := range c.Bars {
		out[i] = market.Candle{Time: 1_790_000_000 + 300*int64(i), Open: b[0], High: b[1], Low: b[2], Close: b[3], Volume: 1}
	}
	return out
}

func sameCandidates(t *testing.T, name string, got []levelCandidate, want []sourceCandidate) {
	t.Helper()
	if len(got) != len(want) {
		t.Errorf("%s: %d candidates, Python %d", name, len(got), len(want))
		return
	}
	for i := range got {
		w := want[i]
		if math.Abs(got[i].Level-w.Level) > 1e-9 || got[i].Source != w.Source || got[i].Subtype != w.Subtype || got[i].Timeframe != w.Timeframe ||
			(got[i].SourceIndex == nil) != (w.SourceIndex == nil) || got[i].SourceIndex != nil && *got[i].SourceIndex != *w.SourceIndex {
			t.Errorf("%s[%d]: Go %+v, Python %+v", name, i, got[i], w)
		}
	}
}

func TestLevelSourcesMatchPython(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "source-cases.json"))
	if err != nil {
		t.Fatal(err)
	}
	var doc struct {
		PipSize float64      `json:"pip_size"`
		Cases   []sourceCase `json:"cases"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		t.Fatal(err)
	}
	pip := doc.PipSize
	boxes, armed, equal, flips := 0, 0, 0, 0
	for _, tc := range doc.Cases {
		bars := tc.candles()
		name := func(part string) string {
			return part + " seed " + string(rune('0'+tc.Seed/10)) + string(rune('0'+tc.Seed%10))
		}
		atr := strategyutil.SetupATR(bars, 14, pip)
		if math.Abs(atr-tc.ATR) > 1e-9 {
			t.Errorf("%s: setup ATR %v, Python %v", name("atr"), atr, tc.ATR)
		}
		micro := buildMicroStructure(bars, 3, 0.5*pip, 2)
		if len(micro.Swings) != len(tc.Swings) {
			t.Errorf("%s: %d swings, Python %d", name("swings"), len(micro.Swings), len(tc.Swings))
		} else {
			for i, s := range micro.Swings {
				if s.Kind != tc.Swings[i][0].(string) || math.Abs(s.Price-tc.Swings[i][1].(float64)) > 1e-9 || s.Index != int(tc.Swings[i][2].(float64)) {
					t.Errorf("%s[%d]: Go %+v, Python %v", name("swing"), i, s, tc.Swings[i])
				}
			}
		}
		for label, pair := range map[string][2][]float64{"equal highs": {micro.EqualHighs, tc.EqualHighs}, "equal lows": {micro.EqualLows, tc.EqualLows}} {
			if len(pair[0]) != len(pair[1]) {
				t.Errorf("%s: %v, Python %v", name(label), pair[0], pair[1])
				continue
			}
			for i := range pair[0] {
				if pair[0][i] != pair[1][i] {
					t.Errorf("%s[%d]: %v, Python %v", name(label), i, pair[0][i], pair[1][i])
				}
			}
			equal += len(pair[0])
		}
		var keyLevels []keyLevel
		for _, kl := range tc.KeyLevels {
			keyLevels = append(keyLevels, keyLevel{Price: kl[0], Touches: int(kl[1])})
		}
		for _, side := range []market.Direction{market.Buy, market.Sell} {
			flip := structureFlipCandidates(micro, side, len(bars)-1, "M5", 3, 240, tc.ATR, 0.3)
			sameCandidates(t, name("structure flip "+string(side)), flip, tc.Flip[string(side)])
			flips += len(flip)
			sameCandidates(t, name("liquidity "+string(side)), liquidityLevelCandidates(micro, side, "M5"), tc.Liquidity[string(side)])
			sameCandidates(t, name("m5 key level "+string(side)), m5StructureFlipCandidates(keyLevels, side, tc.Price, 2), tc.M5[string(side)])
		}
		box := findCompressionBox(bars, tc.ATR, 8, 20, 1.5, 2, 0.20)
		if (box == nil) != (tc.Box == nil) {
			t.Errorf("%s: box %v, Python %v", name("box"), box, tc.Box)
			continue
		}
		if box == nil {
			continue
		}
		boxes++
		if math.Abs(box.Low-tc.Box.Low) > 1e-9 || math.Abs(box.High-tc.Box.High) > 1e-9 || box.Bars != tc.Box.Bars || box.EndIndex != tc.Box.EndIndex || box.TouchCount != tc.Box.Touches {
			t.Errorf("%s: Go %+v, Python %+v", name("box"), *box, *tc.Box)
		}
		minDisplacement := math.Max(pip*3, tc.ATR*0.25)
		for _, side := range []market.Direction{market.Buy, market.Sell} {
			want := tc.Box.Detect[string(side)]
			got := detectBoxBreakRetest(bars, side, box.High, box.Low, minDisplacement, 5, true, box.EndIndex)
			if got.Armed != (want.State == "armed") {
				t.Errorf("%s %s: armed %v, Python state %s", name("box break"), side, got.Armed, want.State)
				continue
			}
			if got.Armed {
				armed++
				if math.Abs(got.Level-*want.Level) > 1e-9 || math.Abs(got.Close-*want.Close) > 1e-9 || math.Abs(got.BreakDisplacement-*want.BreakDisplacement) > 1e-9 {
					t.Errorf("%s %s: Go %+v, Python %+v", name("box break"), side, got, want)
				}
			}
		}
	}
	if boxes < 10 || armed < 2 || equal < 50 || flips < 40 {
		t.Fatalf("the cases no longer exercise the sources: boxes=%d armed=%d equal=%d flips=%d", boxes, armed, equal, flips)
	}
}
