// Package reaction decides whether a closed-bar window shows a confirmed
// reaction off a structural band (a zone, level, or line expressed as
// low/high): a touch followed, on or after the touch bar, by a recognised
// rejection pattern.
//
// It is a faithful port of the legacy Python
// app/analysis/structural_reaction_support.py::evaluate_structural_reaction,
// the single confirmation routine every Python technique shared, so Go
// strategies stop inventing a different (and much stricter) confirmation each.
// Pattern priority, lookback windows and every threshold are the Python
// ones; testdata/reaction-parity.json holds cases generated by running the
// Python function on production captures, and the parity test requires this
// package to return the identical confirmation type and bar indexes.
//
// The package is pure: no zone/level types, no config, no clock.
package reaction

import (
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/market"
)

// Type names are the legacy Python confirmation_type strings, which are also
// what downstream consumers already key on.
const (
	TypeWickRejection  = "wick_rejection"
	TypeSweepReclaim   = "sweep_reclaim"
	TypeRejectionCHoCH = "rejection_choch"
	TypeStrongReclaim  = "strong_reclaim"
	TypeEngulfing      = "engulfing"
)

const epsilon = 1e-12

// Grab is a liquidity grab (sweep then reclaim) the caller found on one bar.
// Only grade "A" and "B" grabs confirm a reaction.
type Grab struct {
	Index int
	Grade string
}

// Params are one evaluation's inputs beyond the candle window.
type Params struct {
	// Direction is "BUY" or "SELL" (the side the reaction favours).
	Direction string
	Low, High float64
	// TouchLookback is how many of the latest bars are searched for a band
	// touch; ConfirmLookback how many for the confirming bar. A confirm
	// lookback <= 0 reuses the touch window. Values below 1 are treated as 1.
	TouchLookback   int
	ConfirmLookback int
	Grabs           []Grab
	HasCHoCH        bool
	// ATR and EngulfingMinimumRangeATR gate the engulfing pattern: when ATR
	// is positive the engulfing bar's range must be at least that fraction
	// of it.
	ATR                      float64
	EngulfingMinimumRangeATR float64
	// MinIndex is the earliest bar that may be a touch or confirmation bar
	// (a structure cannot react before it exists). Zero allows every bar;
	// the bar before MinIndex may still serve as an engulfing bar\'s prior.
	MinIndex int
}

// Confirmation is a found reaction; indexes are positions in the window.
type Confirmation struct {
	Type              string
	TouchIndex        int
	ConfirmationIndex int
}

// Evaluate finds the latest valid confirmation within the lookback windows,
// or nil. Touch and confirmation may be on different bars; the confirmation
// must be on or after its touch.
func Evaluate(candles []market.Candle, p Params) *Confirmation {
	if len(candles) == 0 {
		return nil
	}
	touchLB := p.TouchLookback
	if touchLB < 1 {
		touchLB = 1
	}
	confirmLB := touchLB
	if p.ConfirmLookback > 0 {
		confirmLB = p.ConfirmLookback
	}
	last := len(candles) - 1
	touchEarliest := maxInt(maxInt(0, p.MinIndex), last-touchLB+1)
	confirmEarliest := maxInt(maxInt(0, p.MinIndex), last-confirmLB+1)

	touchIndexes := make([]int, 0, last-touchEarliest+1)
	for i := touchEarliest; i <= last; i++ {
		if bandTouched(candles[i], p.Low, p.High) {
			touchIndexes = append(touchIndexes, i)
		}
	}
	if len(touchIndexes) == 0 {
		return nil
	}

	grabGrade := make(map[int]string, len(p.Grabs))
	for _, g := range p.Grabs {
		if confirmEarliest <= g.Index && g.Index <= last {
			grabGrade[g.Index] = g.Grade
		}
	}

	// Prefer the latest valid confirmation so a stale touch without a fresh
	// confirmation never executes.
	for ci := last; ci >= confirmEarliest; ci-- {
		touchIndex := -1
		for _, ti := range touchIndexes {
			if ti <= ci {
				touchIndex = ti
			}
		}
		if touchIndex < 0 {
			continue
		}
		bar := candles[ci]
		var confirmation string
		switch {
		case grabGrade[ci] == "A" || grabGrade[ci] == "B":
			confirmation = TypeSweepReclaim
		case wickRejection(bar, p.Direction) && p.HasCHoCH:
			confirmation = TypeRejectionCHoCH
		case strongReclaim(bar, p.Direction, p.Low, p.High):
			confirmation = TypeStrongReclaim
		case wickRejection(bar, p.Direction):
			confirmation = TypeWickRejection
		case ci > 0 && engulfing(bar, candles[ci-1], p.Direction, p.ATR, p.EngulfingMinimumRangeATR):
			confirmation = TypeEngulfing
		}
		if confirmation == "" {
			continue
		}
		return &Confirmation{Type: confirmation, TouchIndex: touchIndex, ConfirmationIndex: ci}
	}
	return nil
}

func bandTouched(c market.Candle, low, high float64) bool {
	return c.Low <= high+epsilon && c.High >= low-epsilon
}

// wickRejection: the rejecting wick is at least the body and the bar closes
// in its reaction-side third, in the reaction direction.
func wickRejection(c market.Candle, direction string) bool {
	rng := c.High - c.Low
	if rng <= 0 {
		return false
	}
	body := abs(c.Close - c.Open)
	upper := c.High - maxFloat(c.Open, c.Close)
	lower := minFloat(c.Open, c.Close) - c.Low
	lowerThird := c.Low + rng/3
	upperThird := c.High - rng/3
	if direction == "SELL" {
		return upper >= body && c.Close < c.Open && c.Close <= lowerThird
	}
	return lower >= body && c.Close > c.Open && c.Close >= upperThird
}

// strongReclaim: the wick pierces the band's far edge, then the bar closes
// back through the near edge in the reaction direction.
func strongReclaim(c market.Candle, direction string, low, high float64) bool {
	if direction == "BUY" {
		swept := c.Low < low-epsilon
		reclaimed := c.Close >= low-epsilon && c.Close > c.Open
		return swept && reclaimed
	}
	swept := c.High > high+epsilon
	reclaimed := c.Close <= high+epsilon && c.Close < c.Open
	return swept && reclaimed
}

// engulfing: this bar's body fully engulfs the prior bar's body, the prior
// bar was a doji or opposed the reaction, and (with an ATR) the bar has real
// range.
func engulfing(c, prior market.Candle, direction string, atr, minimumRangeATR float64) bool {
	bodyLow, bodyHigh := minFloat(c.Open, c.Close), maxFloat(c.Open, c.Close)
	priorBodyLow, priorBodyHigh := minFloat(prior.Open, prior.Close), maxFloat(prior.Open, prior.Close)
	if bodyLow > priorBodyLow || bodyHigh < priorBodyHigh {
		return false
	}
	priorRange := maxFloat(prior.High-prior.Low, epsilon)
	priorBodyFraction := abs(prior.Close-prior.Open) / priorRange
	priorBullish := prior.Close > prior.Open+epsilon
	priorBearish := prior.Close < prior.Open-epsilon
	priorOpposite := priorBodyFraction < 0.1 ||
		(direction == "BUY" && priorBearish) ||
		(direction == "SELL" && priorBullish)
	if !priorOpposite {
		return false
	}
	if atr > 0 && (c.High-c.Low) < maxFloat(0, minimumRangeATR)*atr {
		return false
	}
	if direction == "BUY" {
		return c.Close > c.Open
	}
	return c.Close < c.Open
}

func abs(v float64) float64 {
	if v < 0 {
		return -v
	}
	return v
}
func maxFloat(a, b float64) float64 {
	if a > b {
		return a
	}
	return b
}
func minFloat(a, b float64) float64 {
	if a < b {
		return a
	}
	return b
}
func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}
