package reaction_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/market"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/reaction"
)

type goldenCase struct {
	Bars            [][]float64 `json:"bars"`
	Direction       string      `json:"direction"`
	Low             float64     `json:"low"`
	High            float64     `json:"high"`
	TouchLookback   int         `json:"touch_lookback"`
	ConfirmLookback *int        `json:"confirm_lookback"`
	HasCHoCH        bool        `json:"has_choch"`
	ATR             float64     `json:"atr"`
	MinRangeATR     float64     `json:"min_range_atr"`
	Expect          *struct {
		Type         string `json:"type"`
		TouchIndex   int    `json:"touch_index"`
		ConfirmIndex int    `json:"confirm_index"`
	} `json:"expect"`
}

// TestEvaluateMatchesThePythonReferenceOnProductionBars replays 2,500 cases
// generated by running the legacy Python evaluate_structural_reaction on real
// XAU and EURUSD M5 captures (random zones near recent bars, varied lookbacks,
// CHoCH flag, ATR and engulfing threshold). Go must return the identical
// confirmation type and the identical touch/confirmation bar indexes — or
// nothing, exactly when Python returns nothing.
func TestEvaluateMatchesThePythonReferenceOnProductionBars(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("..", "..", "testdata", "reaction-parity.json"))
	if err != nil {
		t.Fatal(err)
	}
	var golden struct {
		Cases []goldenCase `json:"cases"`
	}
	if err := json.Unmarshal(raw, &golden); err != nil {
		t.Fatal(err)
	}
	if len(golden.Cases) < 2000 {
		t.Fatalf("golden file unexpectedly small: %d cases", len(golden.Cases))
	}

	confirmed := 0
	for i, c := range golden.Cases {
		candles := make([]market.Candle, len(c.Bars))
		for j, b := range c.Bars {
			candles[j] = market.Candle{Time: int64(b[0]), Open: b[1], High: b[2], Low: b[3], Close: b[4]}
		}
		confirmLookback := 0
		if c.ConfirmLookback != nil {
			confirmLookback = *c.ConfirmLookback
		}
		got := reaction.Evaluate(candles, reaction.Params{
			Direction: c.Direction, Low: c.Low, High: c.High,
			TouchLookback: c.TouchLookback, ConfirmLookback: confirmLookback,
			HasCHoCH: c.HasCHoCH, ATR: c.ATR, EngulfingMinimumRangeATR: c.MinRangeATR,
		})
		switch {
		case c.Expect == nil && got != nil:
			t.Fatalf("case %d: python found nothing, go found %+v", i, *got)
		case c.Expect != nil && got == nil:
			t.Fatalf("case %d: python found %+v, go found nothing", i, *c.Expect)
		case c.Expect != nil:
			confirmed++
			if got.Type != c.Expect.Type || got.TouchIndex != c.Expect.TouchIndex || got.ConfirmationIndex != c.Expect.ConfirmIndex {
				t.Fatalf("case %d: python %+v, go %+v", i, *c.Expect, *got)
			}
		}
	}
	if confirmed < 800 {
		t.Fatalf("only %d of %d cases carried a confirmation; the golden set no longer exercises the patterns", confirmed, len(golden.Cases))
	}
	t.Logf("%d cases, %d confirmations, all identical to Python", len(golden.Cases), confirmed)
}

func TestEvaluateConfirmsASweepReclaimGrabOnlyAtGradeAOrB(t *testing.T) {
	bars := []market.Candle{
		{Time: 1, Open: 10, High: 11, Low: 9, Close: 10},
		{Time: 2, Open: 10, High: 10.6, Low: 9.4, Close: 10.1},
	}
	base := reaction.Params{Direction: "BUY", Low: 9.5, High: 10.5, TouchLookback: 2}

	base.Grabs = []reaction.Grab{{Index: 1, Grade: "A"}}
	if got := reaction.Evaluate(bars, base); got == nil || got.Type != reaction.TypeSweepReclaim || got.ConfirmationIndex != 1 {
		t.Fatalf("a grade A grab on the latest bar must confirm as sweep_reclaim, got %+v", got)
	}
	base.Grabs = []reaction.Grab{{Index: 1, Grade: "C"}}
	if got := reaction.Evaluate(bars, base); got != nil && got.Type == reaction.TypeSweepReclaim {
		t.Fatalf("a grade C grab must not confirm, got %+v", got)
	}
}
