"""Configuration V3 Stage C6: cross-language parity against the shared
canonical fixture.

`contracts/configuration/examples/resolved-production-v3.json` is
generated by `config/scripts/resolve_reference.py` — a fourth, minimal
reference implementation of §14 whose only job is producing this fixture
and validating it against the JSON Schema. §38 requires that every real
per-language V3 reader (Python's `app/configuration/v3_root.py`, Go's
`analysis-engine/internal/config/v3_document.go`, .NET's
`ctrader-engine/src/ConfigurationV3.cs`) reproduce this exact document
when resolving the real `config/apexvoid.yml` for the production
environment — not that they call the same code, but that four
independent implementations of one spec, run against the same input,
converge on one answer. This file is Python's half of that proof; Go's
is `v3_document_test.go`'s `TestResolveDocumentMatchesCanonicalFixture`;
.NET's is `ConfigurationV3Tests.cs`'s
`ResolveDocumentMatchesCanonicalFixture`.

This is deliberately NOT the same thing as `test_config_v3_parity.py`
(Stage C3): that test proves the *old flat shape* (`ApexVoidConfig`, via
un-consolidation) is unchanged by the V3 cutover. This test proves the
*V3 shape itself* (`resolve_v3_document`'s direct output, before any
un-consolidation) is what every language actually resolves to — the
un-consolidation step is Python-specific plumbing back to old code, not
part of the cross-language contract.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.configuration.v3_root import resolve_v3_document

pytestmark = pytest.mark.no_database

_REPO_ROOT = Path(__file__).resolve().parents[2]
_APEXVOID_YML = _REPO_ROOT / "config" / "apexvoid.yml"
_FIXTURE = _REPO_ROOT / "contracts" / "configuration" / "examples" / "resolved-production-v3.json"


def test_resolve_v3_document_matches_canonical_fixture():
  resolved = resolve_v3_document(_APEXVOID_YML)
  with _FIXTURE.open() as f:
    fixture = json.load(f)
  assert resolved == fixture, (
    "app/configuration/v3_root.py's resolve_v3_document(config/apexvoid.yml) "
    "no longer matches contracts/configuration/examples/resolved-production-v3.json. "
    "Either config/*.yml changed without regenerating the fixture "
    "(algo-bot/.venv/bin/python config/scripts/resolve_reference.py "
    "--environment production --write-fixture) or v3_root.py's resolution "
    "logic diverged from resolve_reference.py's — both must implement §14 "
    "identically."
  )


def test_fixture_declares_production_environment():
  # A cheap guard against the fixture silently being regenerated for the
  # wrong environment — every assertion above is only meaningful if this
  # holds.
  with _FIXTURE.open() as f:
    fixture = json.load(f)
  assert fixture["runtime"]["environment"] == "production"
