// Package scalpparity_test proves the Go Breakout Retest Scalp against the
// Python engine that ran during the profitable XAU week (14–18 Sep 2026). The
// golden is that engine's decision on every closed M1 bar of a committed real
// XAU capture (testdata/scalp-breakout-retest-oracle.json, generated by running
// the Python implementation, never by Go); this test replays the capture
// through the Go engine and requires the same opportunities on the same bars.
package scalpparity_test

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/config"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/engine"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/market"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/opportunity"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/replaycapture"
)

type goldenOpportunity struct {
	Bar       int64   `json:"bar"`
	Direction string  `json:"direction"`
	ZoneLow   float64 `json:"zone_low"`
	ZoneHigh  float64 `json:"zone_high"`
	KeyLevel  float64 `json:"key_level"`
	Invalid   float64 `json:"invalidation"`
	Target    float64 `json:"target"`
	Source    string  `json:"source"`
	Subtype   string  `json:"subtype"`
	Quality   float64 `json:"quality"`
}

type golden struct {
	Capture       string              `json:"capture"`
	Cycles        []int64             `json:"cycles"`
	Opportunities []goldenOpportunity `json:"opportunities"`
}

func TestBreakoutRetestScalpMatchesTheProfitableWeekPython(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("..", "..", "testdata", "scalp-breakout-retest-oracle.json"))
	if err != nil {
		t.Fatal(err)
	}
	var want golden
	if err := json.Unmarshal(data, &want); err != nil {
		t.Fatal(err)
	}
	doc, err := config.ResolveDocument(filepath.Join("..", "..", "..", "config", "apexvoid.yml"))
	if err != nil {
		t.Fatal(err)
	}
	capture, err := replaycapture.Load(filepath.Join("..", "..", "testdata", want.Capture))
	if err != nil {
		t.Fatal(err)
	}
	got := map[int64][]opportunity.Candidate{}
	_, err = replaycapture.Replay(doc, capture, market.M1, replaycapture.Options{OnEvaluation: func(e engine.Evaluation) {
		if e.Timeframe != market.M1 {
			return
		}
		for _, candidate := range e.Candidates {
			if candidate.Strategy == "scalp_breakout_retest" {
				got[e.BarTime] = append(got[e.BarTime], candidate)
			}
		}
	}})
	if err != nil {
		t.Fatal(err)
	}

	cycles := map[int64]bool{}
	for _, bar := range want.Cycles {
		cycles[bar] = true
	}
	wantByBar := map[int64][]goldenOpportunity{}
	for _, o := range want.Opportunities {
		wantByBar[o.Bar] = append(wantByBar[o.Bar], o)
	}
	tick := math.Pow10(-2)
	near := func(a, b float64) bool { return math.Abs(a-b) <= tick+1e-9 }

	var failures []string
	bars := make([]int64, 0, len(cycles))
	for bar := range cycles {
		bars = append(bars, bar)
	}
	sort.Slice(bars, func(i, j int) bool { return bars[i] < bars[j] })
	matched := 0
	for _, bar := range bars {
		expected, actual := wantByBar[bar], got[bar]
		if len(expected) != len(actual) {
			failures = append(failures, "bar mismatch count")
			t.Errorf("bar %d: oracle %d opportunities, Go %d", bar, len(expected), len(actual))
			continue
		}
		sort.Slice(expected, func(i, j int) bool { return expected[i].Direction < expected[j].Direction })
		sort.Slice(actual, func(i, j int) bool { return actual[i].Direction < actual[j].Direction })
		for i := range expected {
			e, a := expected[i], actual[i]
			if string(a.Direction) != e.Direction || !near(a.Entry.Low, e.ZoneLow) || !near(a.Entry.High, e.ZoneHigh) ||
				!near(float64(a.Invalidation.Price), e.Invalid) || !near(float64(a.Targets[0].Price.Price), e.Target) ||
				math.Abs(a.Quality.Overall*100-e.Quality) > 1e-6 {
				t.Errorf("bar %d %s: oracle zone %.3f-%.3f stop %.3f target %.3f quality %.4f source %s; Go zone %.3f-%.3f stop %.3f target %.3f quality %.4f",
					bar, e.Direction, e.ZoneLow, e.ZoneHigh, e.Invalid, e.Target, e.Quality, e.Source,
					a.Entry.Low, a.Entry.High, float64(a.Invalidation.Price), float64(a.Targets[0].Price.Price), a.Quality.Overall*100)
				continue
			}
			matched++
		}
	}
	for bar := range got {
		if !cycles[bar] {
			t.Errorf("Go produced an opportunity on bar %d that the oracle never evaluated", bar)
		}
	}
	if matched != len(want.Opportunities) {
		t.Errorf("matched %d of %d oracle opportunities", matched, len(want.Opportunities))
	}
	if len(want.Opportunities) < 20 {
		t.Fatalf("the golden carries only %d opportunities; it no longer exercises the strategy", len(want.Opportunities))
	}
}
