"""
store.py — PostgreSQL persistence layer for the XAU Signal bot.

The database is reached through ``settings.database_url`` (an asyncpg/libpq DSN,
default ``postgresql://apexvoid:apexvoid@localhost:5432/signals``). A single
lazily-created connection pool is shared across all asyncio tasks; every helper
acquires a connection for the duration of its work and releases it back.

Tables
------
pips_log
  Append-only record of every pips result the bot auto-edits in the channel
  (e.g. "+80 pips" or "-30 pips"). Queried by ``/trade_pips``
  DM command to produce win/loss summaries.

manual_signals
  Lifecycle tracker for every signal posted manually via the bot's DM interface.
  Stores the original Telegram channel message_id so the bot can later reply to
  (or reference) the exact post when the signal is closed or cancelled.

  Status flow:
    open  ──► closed     (via DM "close <id> +pips" or reply "+pips" to channel post)
        ──► cancelled  (via DM "cancel <id>" or reply "cancel" to channel post)
"""

import json
import time
import asyncpg
import logging
from contextlib import asynccontextmanager
from datetime import datetime
from zoneinfo import ZoneInfo
from app.core.config import settings
from app.core.symbols import pip_for

log = logging.getLogger(__name__)

_LEG_EPSILON = 1e-9

# Shared connection pool, created on first use so importing this module never
# opens a socket (keeps unit tests and tooling side-effect free).
_pool: asyncpg.Pool | None = None


async def _get_pool() -> asyncpg.Pool:
  global _pool
  if _pool is None:
    _pool = await asyncpg.create_pool(
      settings.database_url,
      min_size=1,
      max_size=10,
      command_timeout=30,
    )
  return _pool


async def close_pool() -> None:
  """Close the shared pool. Used on shutdown and between tests."""
  global _pool
  if _pool is not None:
    await _pool.close()
    _pool = None


@asynccontextmanager
async def _connect():
  pool = await _get_pool()
  async with pool.acquire() as conn:
    yield conn


def _rowcount(status: str) -> int:
  """Parse asyncpg's command tag (e.g. ``'UPDATE 3'``) into a row count."""
  try:
    return int(status.split()[-1])
  except (ValueError, IndexError, AttributeError):
    return 0


def _current_trade_date() -> str:
  tz = ZoneInfo(settings.seq_reset_tz)
  return datetime.now(tz).date().isoformat()


# ---------------------------------------------------------------------------
# Schema bootstrap
# ---------------------------------------------------------------------------

async def init_db() -> None:
  """Create all tables and indexes if they do not already exist.

  Safe to call on every application startup — every statement uses
  ``IF NOT EXISTS`` so it is a no-op when the schema is already in place.
  Call this once on startup before any other DB function.
  """
  async with _connect() as db:
    # ------------------------------------------------------------------
    # Table: pips_log
    # Appended to whenever the bot auto-edits a channel message that
    # contains a pips result (e.g. "+80 pips").  Used by /trade_pips for
    # local period summaries.
    # ------------------------------------------------------------------
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS pips_log (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ts         BIGINT  NOT NULL,      -- unix timestamp of the edit
        sign       TEXT    NOT NULL,      -- '+' for profit, '-' for loss
        pips       INTEGER NOT NULL,      -- absolute pip count (always positive)
        message_id BIGINT,                -- Telegram message_id that was edited
        chat_id    TEXT,                  -- Telegram chat_id of the channel
        signal_id  BIGINT                 -- linked manual_signals row, if any
      )
      """
    )
    await db.execute("CREATE INDEX IF NOT EXISTS idx_pips_ts ON pips_log(ts)")
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_pips_signal_id ON pips_log(signal_id)"
    )

    # ------------------------------------------------------------------
    # Table: manual_signals
    # Tracks every signal posted to the channel via the bot's DM
    # interface ("gold sell 4100-4105 / sl 4110 / tp 95/90/80").
    # ------------------------------------------------------------------
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS manual_signals (
        id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ts                 BIGINT           NOT NULL,
        action             TEXT             NOT NULL,
        entry              DOUBLE PRECISION NOT NULL,
        entry_end          DOUBLE PRECISION,
        sl                 DOUBLE PRECISION NOT NULL,
        original_sl        DOUBLE PRECISION,
        tps                TEXT             NOT NULL,
        order_type         TEXT             NOT NULL,
        channel_message_id BIGINT,
        status             TEXT             NOT NULL DEFAULT 'open',
        result_pips        INTEGER,
        closed_at          BIGINT,
        daily_seq          INTEGER,
        trade_date         TEXT,
        fill_state         TEXT             NOT NULL DEFAULT 'pending',
        filled_at          BIGINT,
        legs               TEXT             NOT NULL DEFAULT '[]',
        parent_id          BIGINT,
        setup_type         TEXT,
        confluence         INTEGER,
        note               TEXT,
        symbol             TEXT             NOT NULL DEFAULT 'XAU',
        visibility         TEXT             NOT NULL DEFAULT 'both',
        algo_armed         BOOLEAN          NOT NULL DEFAULT FALSE,
        trade_stream       TEXT             NOT NULL DEFAULT 'manual'
      )
      """
    )
    # Migration: original_sl records the stop as first placed and is never
    # updated (update_sl only moves `sl`). Older rows predate the column, so
    # add it idempotently and backfill from the current stop.
    await db.execute(
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS original_sl DOUBLE PRECISION"
    )
    await db.execute(
      "UPDATE manual_signals SET original_sl = sl WHERE original_sl IS NULL"
    )
    # Migration: execution lifecycle columns for the opt-in `/ algo` DM
    # suffix (manual-signal broker execution, PR 2 of 3 — infra only, no
    # broker consumes these yet). Every pre-existing row predates broker
    # execution entirely, so NULL/default is correct for all of them; there
    # is nothing to backfill, unlike original_sl above.
    await db.execute(
      # 'notify' (default, today's behavior) | 'algo' (owner armed broker
      # execution for this signal via the `/ algo` suffix).
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_mode TEXT NOT NULL DEFAULT 'notify'"
    )
    await db.execute(
      # NULL (never armed) | 'armed' | 'filled' | 'closed' | 'cancelled' |
      # 'rejected' | 'error'.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_status TEXT"
    )
    await db.execute(
      # Stable id of the published ManualTradeIntent, 'manual:<id>:<revision>'.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_intent_id TEXT"
    )
    await db.execute(
      # Bumped each time a new intent is published for the same signal
      # (e.g. a re-arm after SL/TP edit) — not used anywhere yet in this PR.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_revision INTEGER NOT NULL DEFAULT 0"
    )
    await db.execute(
      # Broker-side position id once filled. Internal only — never rendered
      # to Telegram.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS broker_position_id TEXT"
    )
    await db.execute(
      # Actual broker fill price, once filled.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS broker_fill_price DOUBLE PRECISION"
    )
    await db.execute(
      # Last error message from an arm/fill/close attempt, if any.
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS execution_error TEXT"
    )
    await db.execute(
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS algo_armed BOOLEAN NOT NULL DEFAULT FALSE"
    )
    await db.execute(
      "ALTER TABLE manual_signals "
      "ADD COLUMN IF NOT EXISTS trade_stream TEXT NOT NULL DEFAULT 'manual'"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_execution_intent_id "
      "ON manual_signals(execution_intent_id)"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_status "
      "ON manual_signals(status)"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_trade_date "
      "ON manual_signals(trade_date)"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_symbol_trade_date "
      "ON manual_signals(symbol, trade_date)"
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_manual_signals_parent_id "
      "ON manual_signals(parent_id)"
    )

    # Broker execution ledger. Fills and results are separate so scale-ins
    # retain their real fill count while one group result remains one trade.
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS auto_trade_fills (
        position_id BIGINT PRIMARY KEY,
        group_id    TEXT             NOT NULL,
        trade_key   TEXT             NOT NULL,
        trade_stream TEXT            NOT NULL,
        symbol      TEXT             NOT NULL DEFAULT 'XAU',
        setup_type  TEXT,
        direction   TEXT,
        entry_price DOUBLE PRECISION,
        stop_pips   DOUBLE PRECISION,
        volume      BIGINT,
        filled_at   BIGINT           NOT NULL
      )
      """
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_auto_trade_fills_group "
      "ON auto_trade_fills(group_id)"
    )
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS auto_trade_results (
        group_id     TEXT PRIMARY KEY,
        trade_key    TEXT             NOT NULL,
        trade_stream TEXT             NOT NULL,
        result_pips  DOUBLE PRECISION NOT NULL,
        closed_at    BIGINT           NOT NULL
      )
      """
    )
    await db.execute(
      "CREATE INDEX IF NOT EXISTS idx_auto_trade_results_closed "
      "ON auto_trade_results(closed_at)"
    )

    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS signal_posts (
        signal_id  BIGINT NOT NULL,
        channel_id BIGINT NOT NULL,
        message_id BIGINT NOT NULL,
        tier       TEXT   NOT NULL,
        PRIMARY KEY (signal_id, channel_id)
      )
      """
    )
    await db.execute(
      "CREATE UNIQUE INDEX IF NOT EXISTS idx_signal_posts_message "
      "ON signal_posts(channel_id, message_id)"
    )
    # Back-fill VIP posts for signals stored before signal_posts existed.
    await db.execute(
      """
      INSERT INTO signal_posts (signal_id, channel_id, message_id, tier)
      SELECT id, $1, channel_message_id, 'vip'
      FROM manual_signals
      WHERE channel_message_id IS NOT NULL
      -- Unqualified DO NOTHING mirrors SQLite's INSERT OR IGNORE: skip a row
      -- that collides on *either* unique constraint (PK or message_id).
      ON CONFLICT DO NOTHING
      """,
      settings.signal_vip_channel_id,
    )

    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS events (
        event_id  TEXT    PRIMARY KEY,
        ts_utc    BIGINT  NOT NULL,
        currency  TEXT    NOT NULL,
        title     TEXT    NOT NULL,
        impact    TEXT    NOT NULL,
        forecast  TEXT,
        previous  TEXT,
        actual    TEXT,
        all_day   INTEGER NOT NULL DEFAULT 0,
        source    TEXT    NOT NULL DEFAULT 'ff',
        synced_at BIGINT  NOT NULL
      )
      """
    )
    await db.execute("CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts_utc)")
    await db.execute(
      """
      CREATE TABLE IF NOT EXISTS meta (
        key   TEXT PRIMARY KEY,
        value TEXT
      )
      """
    )


# ---------------------------------------------------------------------------
# Economic calendar
# ---------------------------------------------------------------------------

async def upsert_events(rows: list[dict]) -> None:
  """Insert calendar events, refreshing release values on repeat syncs."""
  if not rows:
    return
  values = [
    (
      row["event_id"], row["ts_utc"], row["currency"], row["title"],
      row["impact"], row.get("forecast"), row.get("previous"),
      row.get("actual"), row.get("all_day", 0),
      row.get("source", "ff"), row["synced_at"],
    )
    for row in rows
  ]
  async with _connect() as db:
    await db.executemany(
      """
      INSERT INTO events (
        event_id, ts_utc, currency, title, impact, forecast, previous,
        actual, all_day, source, synced_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      ON CONFLICT (event_id) DO UPDATE SET
        forecast = excluded.forecast,
        previous = excluded.previous,
        actual = COALESCE(excluded.actual, events.actual),
        synced_at = excluded.synced_at
      """,
      values,
    )


async def events_between(start_utc: int, end_utc: int) -> list[dict]:
  """Return stored high-impact events in chronological order."""
  async with _connect() as db:
    rows = await db.fetch(
      """
      SELECT * FROM events
      WHERE impact = 'High' AND ts_utc >= $1 AND ts_utc < $2
      ORDER BY ts_utc ASC, title ASC
      """,
      start_utc, end_utc,
    )
  return [dict(row) for row in rows]


async def event_in_window(now: int, horizon: int) -> dict | None:
  """Return the nearest timed event from 30m ago through the horizon."""
  async with _connect() as db:
    row = await db.fetchrow(
      """
      SELECT * FROM events
      WHERE impact = 'High'
        AND all_day = 0
        AND ts_utc >= $1
        AND ts_utc <= $2
      ORDER BY ABS(ts_utc - $3) ASC, ts_utc ASC
      LIMIT 1
      """,
      now - 1800, now + horizon, now,
    )
  return dict(row) if row else None


async def get_meta(key: str) -> str | None:
  async with _connect() as db:
    return await db.fetchval("SELECT value FROM meta WHERE key = $1", key)


async def set_meta(key: str, value: str) -> None:
  async with _connect() as db:
    await db.execute(
      """
      INSERT INTO meta (key, value) VALUES ($1, $2)
      ON CONFLICT (key) DO UPDATE SET value = excluded.value
      """,
      key, value,
    )


# ---------------------------------------------------------------------------
# pips_log helpers
# ---------------------------------------------------------------------------

async def store_pips(
  sign: str,
  pips: int,
  message_id: int = None,
  chat_id: str = None,
  signal_id: int = None,
) -> None:
  """Append one pips result to the log.

  Args:
    sign:       ``'+'`` for a winning trade, ``'-'`` for a loss.
    pips:       Absolute pip count (always positive; sign carries direction).
    message_id: Telegram message_id of the edited channel post (optional).
    chat_id:    Telegram chat_id of the channel (optional).
    signal_id:  Linked manual signal primary key (optional).
  """
  async with _connect() as db:
    await db.execute(
      "INSERT INTO pips_log "
      "(ts, sign, pips, message_id, chat_id, signal_id) "
      "VALUES ($1, $2, $3, $4, $5, $6)",
      int(time.time()), sign, pips, message_id,
      str(chat_id) if chat_id else None, signal_id,
    )


async def get_pips_summary(
  start_ts: int,
  end_ts: int,
  symbol: str | None = None,
) -> dict:
  """Aggregate pips results within a Unix timestamp range.

  Returns:
    A dict with keys:
      wins       — number of winning trades in the period.
      win_pips   — total pips gained from winners.
      losses     — number of losing trades in the period.
      loss_pips  — total pips lost from losers (positive integer).
      net        — net pips (win_pips - loss_pips); negative means net loss.
      total      — total number of trades recorded (wins + losses).
  """
  query = (
    "SELECT p.sign, p.pips FROM pips_log p "
    "LEFT JOIN manual_signals s ON s.id = p.signal_id "
    "WHERE p.ts >= $1 AND p.ts <= $2"
  )
  params: list = [start_ts, end_ts]
  if symbol:
    query += " AND s.symbol = $3"
    params.append(symbol.upper())
  async with _connect() as db:
    records = await db.fetch(query, *params)
  rows = [(r["sign"], r["pips"]) for r in records]
  wins   = [(s, p) for s, p in rows if s == '+']
  losses = [(s, p) for s, p in rows if s == '-']
  net    = sum(p if s == '+' else -p for s, p in rows)
  return {
    'wins': len(wins), 'win_pips': sum(p for _, p in wins),
    'losses': len(losses), 'loss_pips': sum(p for _, p in losses),
    'net': net, 'total': len(rows),
  }


async def get_pips_records(
  start_ts: int,
  end_ts: int,
  symbol: str | None = None,
) -> list[dict]:
  """Return manual and broker execution results, oldest first."""
  query = """
    SELECT p.id, p.ts, p.sign, p.pips, p.signal_id,
           s.ts AS signal_ts, s.action, s.entry, s.entry_end,
           s.parent_id, s.setup_type, s.daily_seq, s.symbol,
           s.original_sl, 'manual'::TEXT AS stream,
           ('manual:' || COALESCE(p.signal_id::TEXT, 'pips:' || p.id::TEXT))
             AS trade_key,
           1::BIGINT AS fill_count
    FROM pips_log p
    LEFT JOIN manual_signals s ON s.id = p.signal_id
    WHERE p.ts >= $1 AND p.ts <= $2
  """
  params: list = [start_ts, end_ts]
  if symbol:
    query += " AND s.symbol = $3"
    params.append(symbol.upper())
  query += " ORDER BY p.ts ASC, p.id ASC"
  async with _connect() as db:
    manual_rows = await db.fetch(query, *params)
    algo_query = """
      SELECT r.group_id AS id, r.closed_at AS ts,
             CASE WHEN r.result_pips >= 0 THEN '+' ELSE '-' END AS sign,
             ABS(ROUND(r.result_pips))::INTEGER AS pips,
             NULL::BIGINT AS signal_id,
             MIN(f.filled_at) AS signal_ts,
             MIN(f.direction) AS action,
             AVG(f.entry_price) AS entry,
             AVG(f.entry_price) AS entry_end,
             NULL::BIGINT AS parent_id,
             MIN(f.setup_type) AS setup_type,
             NULL::INTEGER AS daily_seq,
             MIN(f.symbol) AS symbol,
             NULL::DOUBLE PRECISION AS original_sl,
             r.trade_stream AS stream,
             r.trade_key,
             COUNT(*)::BIGINT AS fill_count,
             AVG(f.stop_pips) AS stop_pips,
             r.result_pips / NULLIF(AVG(f.stop_pips), 0) AS r_multiple
      FROM auto_trade_results r
      JOIN auto_trade_fills f ON f.group_id = r.group_id
      WHERE r.closed_at >= $1 AND r.closed_at <= $2
    """
    algo_params: list = [start_ts, end_ts]
    if symbol:
      algo_query += " AND f.symbol = $3"
      algo_params.append(symbol.upper())
    algo_query += (
      " GROUP BY r.group_id, r.closed_at, r.result_pips, "
      "r.trade_stream, r.trade_key ORDER BY r.closed_at ASC, r.group_id ASC"
    )
    algo_rows = await db.fetch(algo_query, *algo_params)

  records = [dict(row) for row in manual_rows]
  for record in records:
    signal_symbol = record.get("symbol") or "XAU"
    entry = record.get("entry")
    entry_end = record.get("entry_end")
    stop = record.get("original_sl")
    if entry is None or stop is None:
      continue
    reference = (
      entry_end if record.get("action") == "BUY" and entry_end is not None
      else entry
    )
    stop_pips = abs(float(reference) - float(stop)) / pip_for(signal_symbol)
    record["stop_pips"] = stop_pips
    record["r_multiple"] = (
      (record["pips"] if record["sign"] == "+" else -record["pips"])
      / stop_pips
      if stop_pips > 0 else None
    )
  records.extend(dict(row) for row in algo_rows)
  return sorted(records, key=lambda row: (row["ts"], str(row["id"])))


async def record_auto_trade_event(event: dict) -> None:
  """Persist fill attribution and terminal broker results idempotently."""
  event_type = str(event.get("type") or "")
  if event_type in {"opened", "add", "manual_opened"}:
    await _record_auto_trade_fill(event)
  elif event_type in {"group_result", "position_closed", "manual_closed"}:
    await _record_auto_trade_result(event)


async def _record_auto_trade_fill(event: dict) -> None:
  position_id = event.get("position_id")
  stream = str(event.get("stream") or "").strip()
  if position_id is None or stream not in {"algo_auto", "algo_manual"}:
    return
  group_id = str(event.get("group_id") or position_id)
  trade_key = f"algo:{group_id}"
  candidate_id = str(event.get("candidate_id") or "")
  async with _connect() as db:
    if stream == "algo_manual" and candidate_id:
      signal_id = await db.fetchval(
        "SELECT id FROM manual_signals "
        "WHERE execution_intent_id LIKE $1 || '%' "
        "ORDER BY id DESC LIMIT 1",
        candidate_id[:10],
      )
      if signal_id is not None:
        trade_key = f"manual:{signal_id}"
        await db.execute(
          "UPDATE manual_signals SET trade_stream = 'algo_manual' "
          "WHERE id = $1",
          signal_id,
        )
    await db.execute(
      """
      INSERT INTO auto_trade_fills (
        position_id, group_id, trade_key, trade_stream, symbol,
        setup_type, direction, entry_price, stop_pips, volume, filled_at
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
      ON CONFLICT (position_id) DO UPDATE SET
        group_id = excluded.group_id,
        trade_key = excluded.trade_key,
        trade_stream = excluded.trade_stream,
        symbol = excluded.symbol,
        setup_type = COALESCE(excluded.setup_type, auto_trade_fills.setup_type),
        direction = COALESCE(excluded.direction, auto_trade_fills.direction),
        entry_price = COALESCE(excluded.entry_price, auto_trade_fills.entry_price),
        stop_pips = COALESCE(excluded.stop_pips, auto_trade_fills.stop_pips),
        volume = COALESCE(excluded.volume, auto_trade_fills.volume)
      """,
      int(position_id), group_id, trade_key, stream,
      str(event.get("symbol") or "XAU").upper(), event.get("setup"),
      event.get("direction"), event.get("price"), event.get("stop_pips"),
      event.get("volume"), int(event.get("timestamp") or time.time()),
    )


async def _record_auto_trade_result(event: dict) -> None:
  if (
    event.get("type") == "manual_closed"
    and (
      event.get("remaining_volume") is None
      or int(event["remaining_volume"]) > 0
    )
  ):
    return
  group_id = str(event.get("group_id") or "").strip()
  position_id = event.get("position_id")
  async with _connect() as db:
    if not group_id and position_id is not None:
      group_id = str(await db.fetchval(
        "SELECT group_id FROM auto_trade_fills WHERE position_id = $1",
        int(position_id),
      ) or "")
    if not group_id:
      return
    fill = await db.fetchrow(
      "SELECT trade_key, trade_stream FROM auto_trade_fills "
      "WHERE group_id = $1 ORDER BY filled_at ASC LIMIT 1",
      group_id,
    )
    if fill is None:
      return
    if (
      event.get("type") == "position_closed"
      and await db.fetchval(
        "SELECT 1 FROM auto_trade_results WHERE group_id = $1", group_id,
      )
    ):
      return
    result_pips = event.get("group_realized_pips")
    if result_pips is None and event.get("type") in {
      "position_closed", "manual_closed",
    }:
      exit_price = event.get("price")
      if exit_price is None:
        return
      fills = await db.fetch(
        "SELECT symbol, direction, entry_price, volume "
        "FROM auto_trade_fills WHERE group_id = $1",
        group_id,
      )
      weighted = 0.0
      total_volume = 0
      for row in fills:
        if row["entry_price"] is None:
          continue
        volume = int(row["volume"] or 1)
        move = float(exit_price) - float(row["entry_price"])
        if str(row["direction"]).upper() == "SELL":
          move = -move
        weighted += move / pip_for(row["symbol"] or "XAU") * volume
        total_volume += volume
      if not total_volume:
        return
      result_pips = weighted / total_volume
    if result_pips is None:
      return
    await db.execute(
      """
      INSERT INTO auto_trade_results (
        group_id, trade_key, trade_stream, result_pips, closed_at
      ) VALUES ($1, $2, $3, $4, $5)
      ON CONFLICT (group_id) DO UPDATE SET
        trade_key = excluded.trade_key,
        trade_stream = excluded.trade_stream,
        result_pips = excluded.result_pips,
        closed_at = excluded.closed_at
      """,
      group_id, fill["trade_key"], fill["trade_stream"],
      float(result_pips), int(event.get("timestamp") or time.time()),
    )


# ---------------------------------------------------------------------------
# Manual signal lifecycle
# ---------------------------------------------------------------------------

async def store_manual_signal(
  ts: int,
  action: str,
  entry: float,
  entry_end: float,
  sl: float,
  tps: list[float],
  channel_message_id: int | None = None,
  parent_id: int | None = None,
  setup_type: str | None = None,
  confluence: int | None = None,
  symbol: str = "XAU",
  visibility: str = "both",
  execution_mode: str = "notify",
) -> dict:
  """Insert a manual signal and return its primary and daily display ids.

  Args:
    execution_mode: ``'notify'`` (default) posts to the channel only, as
      today. ``'algo'`` additionally arms broker-side execution (handled by
      the caller — this function only persists the flag, it does not branch
      on it).

  Returns:
    A dict containing the primary key ``id`` and today's ``daily_seq``.
  """
  symbol = symbol.upper()
  visibility = visibility.lower()
  if visibility not in {"both", "vip"}:
    raise ValueError(f"Invalid visibility: {visibility}")
  trade_date = _current_trade_date()
  async with _connect() as db:
    async with db.transaction():
      # Serialize concurrent inserts scoped to (symbol, trade_date) so the
      # daily_seq numbering stays gapless, mirroring the old BEGIN IMMEDIATE.
      await db.execute(
        "SELECT pg_advisory_xact_lock(hashtextextended($1, 0))",
        f"{symbol}:{trade_date}",
      )
      count = await db.fetchval(
        "SELECT COUNT(*) FROM manual_signals "
        "WHERE symbol = $1 AND trade_date = $2",
        symbol, trade_date,
      )
      daily_seq = count + 1
      new_id = await db.fetchval(
        """
        INSERT INTO manual_signals
          (ts, action, entry, entry_end, sl, original_sl, tps, order_type,
           channel_message_id, daily_seq, trade_date, parent_id,
           setup_type, confluence, symbol, visibility, execution_mode)
        VALUES ($1, $2, $3, $4, $5, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
        RETURNING id
        """,
        ts, action, entry, entry_end, sl, json.dumps(tps), "zone",
        channel_message_id, daily_seq, trade_date, parent_id,
        setup_type, confluence, symbol, visibility, execution_mode,
      )
  return {
    "id": new_id,
    "daily_seq": daily_seq,
    "symbol": symbol,
    "visibility": visibility,
  }


async def set_manual_signal_channel_id(row_id: int, channel_message_id: int) -> None:
  """Back-fill the channel_message_id for an already-inserted manual signal."""
  async with _connect() as db:
    async with db.transaction():
      await db.execute(
        "UPDATE manual_signals SET channel_message_id = $1 WHERE id = $2",
        channel_message_id, row_id,
      )
      await db.execute(
        """
        INSERT INTO signal_posts (signal_id, channel_id, message_id, tier)
        VALUES ($1, $2, $3, 'vip')
        ON CONFLICT (signal_id, channel_id) DO UPDATE SET
          message_id = excluded.message_id,
          tier = 'vip'
        """,
        row_id, settings.signal_vip_channel_id, channel_message_id,
      )


async def insert_signal_post(
  signal_id: int,
  channel_id: int,
  message_id: int,
  tier: str,
) -> None:
  """Record one delivered signal post and retain the VIP compatibility id."""
  async with _connect() as db:
    async with db.transaction():
      await db.execute(
        """
        INSERT INTO signal_posts (signal_id, channel_id, message_id, tier)
        VALUES ($1, $2, $3, $4)
        ON CONFLICT (signal_id, channel_id) DO UPDATE SET
          message_id = excluded.message_id,
          tier = excluded.tier
        """,
        signal_id, int(channel_id), message_id, tier,
      )
      if tier == "vip":
        await db.execute(
          "UPDATE manual_signals SET channel_message_id = $1 WHERE id = $2",
          message_id, signal_id,
        )


async def get_signal_posts(signal_id: int) -> list[dict]:
  async with _connect() as db:
    rows = await db.fetch(
      "SELECT * FROM signal_posts WHERE signal_id = $1 "
      "ORDER BY CASE tier WHEN 'vip' THEN 0 ELSE 1 END, channel_id",
      signal_id,
    )
  return [dict(row) for row in rows]


async def get_signal_by_post(
  channel_id: int,
  message_id: int,
  *,
  open_only: bool = False,
) -> dict | None:
  if open_only:
    await expire_unfilled_pending_signals()
  query = (
    "SELECT s.* FROM signal_posts p "
    "JOIN manual_signals s ON s.id = p.signal_id "
    "WHERE p.channel_id = $1 AND p.message_id = $2"
  )
  if open_only:
    query += " AND s.status = 'open'"
  async with _connect() as db:
    row = await db.fetchrow(query, int(channel_id), message_id)
  return _decode_signal(row) if row else None


async def get_open_signals(symbol: str | None = None) -> list[dict]:
  """Return all signals currently in ``status = 'open'``, oldest first."""
  await expire_unfilled_pending_signals()
  query = (
    "SELECT id, ts, action, entry, entry_end, sl, tps, "
    "channel_message_id, daily_seq, trade_date, fill_state, filled_at, legs, "
    "parent_id, setup_type, confluence, note, status, result_pips, "
    "symbol, visibility, algo_armed "
    "FROM manual_signals WHERE status = 'open'"
  )
  params: list = []
  if symbol:
    query += " AND symbol = $1"
    params.append(symbol.upper())
  query += " ORDER BY ts ASC"
  async with _connect() as db:
    rows = await db.fetch(query, *params)
  return [_decode_signal(r) for r in rows]


async def expire_unfilled_pending_signals() -> list[dict]:
  """Cancel pending open signals that did not fill on their trade date."""
  today = _current_trade_date()
  now = int(time.time())
  async with _connect() as db:
    rows = await db.fetch(
      """
      UPDATE manual_signals
      SET status = 'cancelled', closed_at = $1, algo_armed = FALSE
      WHERE status = 'open'
        AND fill_state = 'pending'
        AND (trade_date IS NULL OR trade_date < $2)
      RETURNING *
      """,
      now, today,
    )
  if rows:
    log.info("Auto-cancelled %s stale pending signal(s)", len(rows))
  return [_decode_signal(row) for row in rows]


def _decode_signal(row) -> dict:
  """Convert one signal row to a dict and deserialize its JSON fields."""
  result = dict(row)
  result["tps"] = json.loads(result.get("tps") or "[]")
  result["legs"] = json.loads(result.get("legs") or "[]")
  return result


async def get_all_signals(symbol: str | None = None) -> list[dict]:
  """Return every manual signal, oldest first."""
  query = "SELECT * FROM manual_signals"
  params: list = []
  if symbol:
    query += " WHERE symbol = $1"
    params.append(symbol.upper())
  query += " ORDER BY ts ASC, id ASC"
  async with _connect() as db:
    rows = await db.fetch(query, *params)
  return [_decode_signal(row) for row in rows]


async def get_untagged_signals(limit: int = 20) -> list[dict]:
  """Return recent signals whose setup metadata still needs backfilling."""
  limit = max(1, min(100, int(limit)))
  async with _connect() as db:
    rows = await db.fetch(
      "SELECT * FROM manual_signals "
      "WHERE setup_type IS NULL "
      "ORDER BY ts DESC, id DESC LIMIT $1",
      limit,
    )
  return [_decode_signal(row) for row in rows]


async def get_manual_signal(row_id: int) -> dict | None:
  """Return one signal by primary key, regardless of lifecycle state."""
  async with _connect() as db:
    row = await db.fetchrow(
      "SELECT * FROM manual_signals WHERE id = $1", row_id,
    )
  return _decode_signal(row) if row else None


async def undo_last_close_leg(row_id: int) -> dict | None:
  """Undo the latest close booking and leave the signal open again.

  Used for operator mistakes: the trade was marked closed in the bot, but is
  still running in reality. If the signal had partial legs, only the most
  recent leg is removed so earlier intentional scale-outs remain intact.
  Final-close accounting rows linked to the signal are removed from pips_log.
  """
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 FOR UPDATE", row_id,
      )
      if row is None or row["status"] == "cancelled":
        return None

      legs = json.loads(row["legs"] or "[]")
      if row["status"] == "open" and not legs:
        return None

      restored_leg = legs.pop() if legs else None
      remaining = max(
        0.0,
        1.0 - sum(float(leg["frac"]) for leg in legs),
      )
      await db.execute(
        "UPDATE manual_signals "
        "SET status = 'open', result_pips = NULL, closed_at = NULL, "
        "legs = $1 WHERE id = $2",
        json.dumps(legs), row_id,
      )
      await db.execute(
        "DELETE FROM pips_log WHERE signal_id = $1", row_id,
      )
    return {
      **_decode_signal(row),
      "status": "open",
      "result_pips": None,
      "closed_at": None,
      "legs": legs,
      "restored_leg": restored_leg,
      "remaining": remaining,
      "previous_status": row["status"],
    }


async def get_manual_signal_any_by_channel_id(
  channel_message_id: int,
) -> dict | None:
  """Return a signal by channel message id, regardless of lifecycle state."""
  async with _connect() as db:
    row = await db.fetchrow(
      "SELECT * FROM manual_signals WHERE channel_message_id = $1",
      channel_message_id,
    )
  return _decode_signal(row) if row else None


def signal_root(signal: dict) -> int:
  """Return the single-hop root id for a signal or re-entry round."""
  return signal.get("parent_id") or signal["id"]


async def get_signal_cluster(row_id: int) -> list[dict]:
  """Return the root and all linked re-entry rounds for one signal."""
  source = await get_manual_signal(row_id)
  if source is None:
    return []
  root_id = signal_root(source)
  async with _connect() as db:
    rows = await db.fetch(
      "SELECT * FROM manual_signals "
      "WHERE id = $1 OR parent_id = $2 "
      "ORDER BY CASE WHEN id = $3 THEN 0 ELSE 1 END, ts ASC, id ASC",
      root_id, root_id, root_id,
    )
  return [_decode_signal(row) for row in rows]


async def update_setup(
  row_id: int,
  setup_type: str,
  confluence: int | None,
) -> bool:
  """Set or replace setup metadata on any signal."""
  async with _connect() as db:
    status = await db.execute(
      "UPDATE manual_signals SET setup_type = $1, confluence = $2 WHERE id = $3",
      setup_type.lower(), confluence, row_id,
    )
  return _rowcount(status) > 0


async def set_note(row_id: int, note: str) -> bool:
  """Set or replace the journal note on any signal."""
  async with _connect() as db:
    status = await db.execute(
      "UPDATE manual_signals SET note = $1 WHERE id = $2",
      note, row_id,
    )
  return _rowcount(status) > 0


async def mark_filled(row_id: int) -> dict | None:
  """Mark a pending open signal filled and return its pre-update row."""
  await expire_unfilled_pending_signals()
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals "
        "WHERE id = $1 AND status = 'open' AND fill_state = 'pending' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      await db.execute(
        "UPDATE manual_signals SET fill_state = 'filled', filled_at = $1 "
        "WHERE id = $2 AND status = 'open' AND fill_state = 'pending'",
        int(time.time()), row_id,
      )
    return dict(row)


async def close_leg(
  row_id: int,
  pips: int,
  frac: float | None = None,
) -> dict | None:
  """Book one scale-out leg and close the signal when no size remains."""
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None

      legs = json.loads(row["legs"] or "[]")
      used = sum(float(leg["frac"]) for leg in legs)
      remaining = max(0.0, 1.0 - used)
      close_frac = remaining if frac is None else frac
      result_base = {
        "id": row["id"],
        "channel_message_id": row["channel_message_id"],
        "daily_seq": row["daily_seq"],
        "symbol": row["symbol"],
        "visibility": row["visibility"],
      }
      if close_frac <= 0 or close_frac > remaining + _LEG_EPSILON:
        return {
          **result_base,
          "error": "exceeds_remaining",
          "remaining": remaining,
        }

      now = int(time.time())
      legs.append({"frac": close_frac, "pips": pips, "ts": now})
      new_remaining = 1.0 - sum(float(leg["frac"]) for leg in legs)
      if new_remaining <= _LEG_EPSILON:
        net = round(
          sum(float(leg["frac"]) * int(leg["pips"]) for leg in legs)
        )
        await db.execute(
          "UPDATE manual_signals SET status = 'closed', result_pips = $1, "
          "closed_at = $2, legs = $3 WHERE id = $4 AND status = 'open'",
          net, now, json.dumps(legs), row_id,
        )
        return {
          **result_base,
          "closed": True,
          "net": net,
          "remaining": 0.0,
          "frac": close_frac,
        }

      await db.execute(
        "UPDATE manual_signals SET legs = $1 "
        "WHERE id = $2 AND status = 'open'",
        json.dumps(legs), row_id,
      )
    return {
      **result_base,
      "closed": False,
      "net": None,
      "remaining": new_remaining,
      "frac": close_frac,
    }


async def update_sl(row_id: int, price: float) -> dict | None:
  """Move the stop loss on an open signal and return its previous row."""
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      await db.execute(
        "UPDATE manual_signals SET sl = $1 WHERE id = $2 AND status = 'open'",
        price, row_id,
      )
    return dict(row)


async def set_execution_intent(
  signal_id: int,
  *,
  intent_id: str,
  status: str,
  revision: int,
) -> dict | None:
  """Attach a freshly published ManualTradeIntent to its signal row.

  Returns the updated row, or ``None`` if ``signal_id`` does not exist.
  """
  async with _connect() as db:
    row = await db.fetchrow(
      "UPDATE manual_signals SET execution_intent_id = $1, "
      "execution_status = $2, execution_revision = $3, algo_armed = TRUE "
      "WHERE id = $4 RETURNING *",
      intent_id, status, revision, signal_id,
    )
  return _decode_signal(row) if row else None


async def set_execution_status(
  signal_id: int,
  status: str,
  *,
  error: str | None = None,
) -> dict | None:
  """Update the execution lifecycle status (and optional error) on a signal.

  Returns the updated row, or ``None`` if ``signal_id`` does not exist.
  """
  async with _connect() as db:
    clear_armed = status in {"cancelled", "expired", "rejected"}
    row = await db.fetchrow(
      "UPDATE manual_signals SET execution_status = $1, execution_error = $2, "
      "algo_armed = CASE WHEN $3 AND broker_position_id IS NULL "
      "THEN FALSE ELSE algo_armed END WHERE id = $4 RETURNING *",
      status, error, clear_armed, signal_id,
    )
  return _decode_signal(row) if row else None


async def set_execution_fill(
  signal_id: int,
  *,
  broker_position_id: int,
  broker_fill_price: float,
) -> dict | None:
  """Record a manual-algo limit order's real broker fill.

  Called once (from the reconcile loop) when AutoTradeEngine.cs's fill
  adoption reconstructs the position and publishes its "manual_opened"
  event — marks the signal ``'filled'`` and records the real position id
  and fill price the owner-override commands (``/trade_close``/``/trade_sl``)
  need to route to the broker afterwards.

  Returns the updated row, or ``None`` if ``signal_id`` does not exist.
  """
  async with _connect() as db:
    row = await db.fetchrow(
      "UPDATE manual_signals SET execution_status = 'filled', algo_armed = TRUE, "
      "trade_stream = 'algo_manual', broker_position_id = $1, "
      "broker_fill_price = $2 WHERE id = $3 "
      "RETURNING *",
      str(broker_position_id), broker_fill_price, signal_id,
    )
  return _decode_signal(row) if row else None


async def get_signal_by_execution_intent_id(intent_token: str) -> dict | None:
  """Look up a manual signal by its ``execution_intent_id``.

  Tolerates the truncated identity cTrader comments carry: comment fields
  are capped at 100 chars broker-side, so AutoTradeEngine.cs embeds only
  ``CandidateToken(intent_id)`` (the first 10 characters) in a manual-algo
  position/order comment — the same truncation convention every other
  candidate type in this codebase already accepts for comment-based
  identity matching. Matching by prefix means either the full
  ``execution_intent_id`` or that truncated token resolves the same row.
  On the rare (and, for this single-owner bot, extremely unlikely) case of
  two signals sharing a 10-character prefix, the most recently created
  match wins.
  """
  async with _connect() as db:
    row = await db.fetchrow(
      "SELECT * FROM manual_signals WHERE execution_intent_id LIKE $1 || '%' "
      "ORDER BY id DESC LIMIT 1",
      intent_token[:10],
    )
  return _decode_signal(row) if row else None


async def get_manual_signal_by_channel_id(channel_message_id: int) -> dict | None:
  """Look up an open manual signal by its Telegram channel message_id."""
  async with _connect() as db:
    row = await db.fetchrow(
      "SELECT * FROM manual_signals "
      "WHERE channel_message_id = $1 AND status = 'open'",
      channel_message_id,
    )
    return dict(row) if row else None


async def close_manual_signal(row_id: int, result_pips: int) -> dict | None:
  """Mark a signal as closed and record the pip result.

  Returns:
    The row dict as it was *before* the update (so ``channel_message_id``
    is available for the channel reply), or ``None`` if the signal was not
    found or was already closed/cancelled.
  """
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      await db.execute(
        "UPDATE manual_signals SET status = 'closed', result_pips = $1, "
        "closed_at = $2 WHERE id = $3",
        result_pips, int(time.time()), row_id,
      )
    return dict(row)


async def cancel_manual_signal_by_channel_id(channel_message_id: int) -> dict | None:
  """Cancel an open signal identified by the Telegram channel message_id."""
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals "
        "WHERE channel_message_id = $1 AND status = 'open' "
        "FOR UPDATE",
        channel_message_id,
      )
      if row is None:
        return None
      row = dict(row)
      await db.execute(
        "UPDATE manual_signals SET status = 'cancelled', closed_at = $1 "
        "WHERE id = $2",
        int(time.time()), row["id"],
      )
    return row


async def cancel_manual_signal(row_id: int) -> dict | None:
  """Cancel an open signal by its primary key."""
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 AND status = 'open' "
        "FOR UPDATE",
        row_id,
      )
      if row is None:
        return None
      await db.execute(
        "UPDATE manual_signals SET status = 'cancelled', closed_at = $1 "
        "WHERE id = $2",
        int(time.time()), row_id,
      )
    return dict(row)


async def delete_manual_signal(row_id: int) -> dict | None:
  """Hard-delete a mistyped signal, unlike ``cancel`` which keeps the record.

  Removes the row plus its delivered posts and accounting rows, and returns
  the deleted signal with a ``posts`` list so the caller can also delete the
  channel messages. Returns ``None`` if the signal is gone, or a dict with
  ``{"error": "has_rounds"}`` when re-entry rounds point at it — deleting then
  would orphan later rounds, so cancel (or delete the rounds first) instead.
  """
  async with _connect() as db:
    async with db.transaction():
      row = await db.fetchrow(
        "SELECT * FROM manual_signals WHERE id = $1 FOR UPDATE", row_id,
      )
      if row is None:
        return None
      child = await db.fetchrow(
        "SELECT 1 FROM manual_signals WHERE parent_id = $1 LIMIT 1", row_id,
      )
      if child is not None:
        return {"error": "has_rounds"}
      posts = await db.fetch(
        "SELECT * FROM signal_posts WHERE signal_id = $1", row_id,
      )
      await db.execute("DELETE FROM pips_log WHERE signal_id = $1", row_id)
      await db.execute("DELETE FROM signal_posts WHERE signal_id = $1", row_id)
      await db.execute("DELETE FROM manual_signals WHERE id = $1", row_id)
    return {**_decode_signal(row), "posts": [dict(post) for post in posts]}
