"""Complete Canonical Catalog V2 configuration domain. """
from pydantic import AliasChoices
from pydantic import Field
from pydantic import field_validator
from app.configuration.metadata import ConfigKind
from app.configuration.metadata import ConfigOwner
from app.configuration.metadata import ConfigUnit
from app.configuration.metadata import ContextDefault
from app.configuration.metadata import DefaultContext
from app.configuration.metadata import MismatchPolicy
from app.configuration.metadata import ReloadPolicy
from app.configuration.metadata import RiskClassification
from app.configuration.metadata import config_field
from app.configuration.models.base import FrozenConfigModel

class StrategiesAutoScalpBoxConfig(FrozenConfigModel):
    break_buffer_atr: float = config_field(0.12, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.break_buffer_atr.', validation_summary='none; source constant')
    break_confirmation_closes: int = config_field(2, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.break_confirmation_closes.', validation_summary='none; source constant')
    lookback_bars: int = config_field(60, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.lookback_bars.', validation_summary='none; source constant')
    maximum_close_efficiency: float = config_field(0.45, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.maximum_close_efficiency.', validation_summary='none; source constant')
    maximum_touch_band_pips: int = config_field(6, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.maximum_touch_band_pips.', validation_summary='none; source constant')
    maximum_width_pips: int = config_field(120, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.maximum_width_pips.', validation_summary='none; source constant')
    minimum_body_fraction: float = config_field(0.15, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_body_fraction.', validation_summary='none; source constant')
    minimum_inside_ratio: float = config_field(0.82, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_inside_ratio.', validation_summary='none; source constant')
    minimum_touch_band_pips: float = config_field(2.5, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_touch_band_pips.', validation_summary='none; source constant')
    minimum_touch_episodes: int = config_field(2, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_touch_episodes.', validation_summary='none; source constant')
    minimum_wick_fraction: float = config_field(0.15, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_wick_fraction.', validation_summary='none; source constant')
    minimum_width_pips: int = config_field(55, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.minimum_width_pips.', validation_summary='none; source constant')
    recovery_atr: float = config_field(0.15, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.recovery_atr.', validation_summary='none; source constant')
    touch_band_atr: float = config_field(0.18, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.box.touch_band_atr.', validation_summary='none; source constant')

class StrategiesAutoScalpLookbacksConfig(FrozenConfigModel):
    m15_bars: int = config_field(64, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.lookbacks.m15_bars.', validation_summary='none; source constant')
    m1_bars: int = config_field(120, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.lookbacks.m1_bars.', validation_summary='none; source constant')
    m5_bars: int = config_field(96, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.lookbacks.m5_bars.', validation_summary='none; source constant')

class StrategiesAutoScalpConfig(FrozenConfigModel):
    box: StrategiesAutoScalpBoxConfig = Field(default_factory=StrategiesAutoScalpBoxConfig)
    execution_timeframe: str = config_field('M1', canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.ENUM, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Config-like hardcoded value proposed at strategies.auto_scalp.execution_timeframe.', validation_summary='none; source constant')
    lookbacks: StrategiesAutoScalpLookbacksConfig = Field(default_factory=StrategiesAutoScalpLookbacksConfig)

class StrategiesCounterTrendConfig(FrozenConfigModel):
    allow_counter_trend: bool = config_field(True, canonical_env='ALLOW_COUNTER_TREND', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesSelectionConfig(FrozenConfigModel):
    box_breakout_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_BOX_BREAKOUT_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    momentum_ride_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_MOMENTUM_RIDE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    retest_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_RETEST_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    snap_back_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_SNAP_BACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesBreakoutConfig(FrozenConfigModel):
    break_retest_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_BREAK_RETEST_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    breakout_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_BREAKOUT_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class StrategiesReactionDemandConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_DEMAND_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesReactionKeyLevelOpposingStructureConfig(FrozenConfigModel):
    """Opposing Structure V2 (2026-09 Key Level repair). Every threshold
    here is provisional pending replay evidence (§51 of the repair spec:
    "do not overfit from a few days") - Phase 1 of this repair persists
    them as telemetry inputs only; nothing reads require_strong_
    confirmation_below_r/m1_required_below_room_r/minimum_candle_score_
    tight_room/critical_room_r/tight_room_r yet (that's the deferred
    Phase 3 hard-enforcement stage, once this stage's telemetry has real
    trades to calibrate against). strength_score_ceiling/caution_room_r
    ARE read now, by evaluate_opposing_structure_v2's shadow telemetry
    computation (structural_target_room.py).
    """
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_KEY_LEVEL_OPPOSING_STRUCTURE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Whether Opposing Structure V2 evidence is computed for Key Level at all. Shadow telemetry only in this phase - does not gate activation either way.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    strength_score_ceiling: float = config_field(15.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.SCORE, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Opposing Structure V2: zone.score ceiling normalized to strength_score=1.0. Provisional - typical zone.score observed in production ranges roughly 3-15 (see app/analysis/zones.py _score_zone); no existing config wires this weight today.', validation_summary='none; source constant')
    caution_room_r: float = config_field(2.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.RATIO, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Opposing Structure V2: room_r at or beyond which room_pressure_score is 0 (no immediate entry penalty). Provisional, matches the repair spec\'s own suggested default.', validation_summary='none; source constant')
    critical_room_r: float = config_field(0.5, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.RATIO, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Opposing Structure V2 (Phase 3, not yet enforced): room_r below this would hard-reject. Provisional; the field is added now so a later change only needs to start reading it, not add it.', validation_summary='none; source constant')
    tight_room_r: float = config_field(1.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.RATIO, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Opposing Structure V2 (Phase 3, not yet enforced): room_r below this would require stronger confirmation. Provisional; not yet read by anything.', validation_summary='none; source constant')
    require_strong_confirmation_below_r: float = config_field(1.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.RATIO, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Opposing Structure V2 (Phase 3, not yet enforced): below this room_r, only a strong candle/structural confirmation family may proceed. Provisional; not yet read by anything.', validation_summary='none; source constant')
    m1_required_below_room_r: float = config_field(1.0, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.RATIO, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Opposing Structure V2 (Phase 3, not yet enforced): below this room_r, a fresh directional M1 trigger would be required. Provisional; not yet read by anything.', validation_summary='none; source constant')
    minimum_candle_score_tight_room: float = config_field(0.70, canonical_env=None, owner=ConfigOwner.PYTHON, reload=ReloadPolicy.CODE_RELEASE, runtime_reload=ReloadPolicy.CODE_RELEASE, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, kind=ConfigKind.ALGORITHM_CONSTANT, description='Opposing Structure V2 (Phase 3, not yet enforced): minimum Candle Confirmation V2 final_score accepted as "strong" confirmation in a tight-room band. Provisional; not yet read by anything.', validation_summary='none; source constant')
    missing_opposing_context_policy: str = config_field('wait', canonical_env='AUTO_TRADE_KEY_LEVEL_MISSING_OPPOSING_CONTEXT_POLICY', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Opposing Structure V2 (Phase 3, not yet enforced): fail-safe policy at activation when required HTF zone context is unavailable/stale. Provisional; not yet read by anything.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'wait'),), allowed_values=('wait', 'observe', 'block'), validation_summary='Pydantic enum pattern', pattern='^(wait|observe|block)$')

class StrategiesReactionKeyLevelConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_KEY_LEVEL_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    # Quality gates (off globally; enable per-instrument via overrides). Dig
    # 2026-08-25: GBPJPY Key Level was 0/4 and −118 pips — mostly Asia/
    # outside + ambiguous / counter-bias prints. Keep the detector live;
    # raise the bar instead of disabling the family.
    require_explicit_role: bool = config_field(False, canonical_env='AUTO_TRADE_KEY_LEVEL_REQUIRE_EXPLICIT_ROLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Skip ambiguous-role Key Level (explicit support/resistance kind only).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    require_killzone: bool = config_field(False, canonical_env='AUTO_TRADE_KEY_LEVEL_REQUIRE_KILLZONE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Require killzone for Key Level even when global reaction_require_killzone is off.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    # Deprecated for Key Level bias veto: detector ignores this flag so
    # counter-bias is never HTF-blocked. Prefer min_sell_zone_score.
    require_htf_alignment: bool = config_field(False, canonical_env='AUTO_TRADE_KEY_LEVEL_REQUIRE_HTF_ALIGNMENT', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Deprecated no-op for Key Level: counter-bias is never HTF-vetoed. Use min_sell_zone_score for quality.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    # SELL quality without killing counter-bias: nearest same-side zone score
    # (0 = off). Manual XAU replay: KL SELL zone≥10 WR ~78% vs below ~59%.
    min_sell_zone_score: float = config_field(0.0, canonical_env='AUTO_TRADE_KEY_LEVEL_MIN_SELL_ZONE_SCORE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SCORE, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum nearest same-side zone score for Key Level SELL (0 disables). Does not block counter-bias.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.0),), validation_summary='Pydantic required/type coercion only')
    min_grade: str = config_field('B', canonical_env='AUTO_TRADE_KEY_LEVEL_MIN_GRADE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum ZoneWatch grade for Key Level Reaction (A or B).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'B'),), allowed_values=('A', 'B'), validation_summary='Pydantic type coercion + field validator', pattern='^[AB]$')
    opposing_structure: StrategiesReactionKeyLevelOpposingStructureConfig = Field(default_factory=StrategiesReactionKeyLevelOpposingStructureConfig)

    @field_validator('min_grade', mode='before')
    @classmethod
    def normalize_min_grade(cls, value):
        return value.strip().upper() if isinstance(value, str) else value

class StrategiesReactionLiquidityReversalConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_LIQUIDITY_REVERSAL_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class StrategiesReactionSessionLevelConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_SESSION_LEVEL_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesReactionSupplyConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_SUPPLY_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesReactionTrendlineConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TRENDLINE_REACTION_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    reject_exhausted: bool = config_field(True, canonical_env='AUTO_TRADE_TRENDLINE_REJECT_EXHAUSTED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Skip trendline reaction when the line is marked exhausted.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    maximum_bars_since_last_touch: int | None = config_field(None, canonical_env='AUTO_TRADE_TRENDLINE_MAX_BARS_SINCE_TOUCH', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Optional strategy override for stale last-touch age; None inherits analysis.trendlines.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, None),), validation_summary='Pydantic required/type coercion only')
    maximum_fit_error_atr: float | None = config_field(None, canonical_env='AUTO_TRADE_TRENDLINE_MAX_FIT_ERROR_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Optional strategy override for fit error; None inherits analysis.trendlines.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, None),), validation_summary='Pydantic required/type coercion only')
    require_htf_aligned: bool = config_field(False, canonical_env='AUTO_TRADE_TRENDLINE_REQUIRE_HTF_ALIGNED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Require HTF bias aligned with trendline reaction direction.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    require_killzone: bool = config_field(False, canonical_env='AUTO_TRADE_TRENDLINE_REQUIRE_KILLZONE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Require killzone for Trendline Reaction even when global reaction_require_killzone is off.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    minimum_grade: str | None = config_field(None, canonical_env='AUTO_TRADE_TRENDLINE_MIN_GRADE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Optional minimum ZoneWatch grade for Trendline Reaction; empty/None leaves unset.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, None),), allowed_values=('A', 'B'), validation_summary='Pydantic type coercion + field validator')

    @field_validator('minimum_grade', mode='before')
    @classmethod
    def normalize_minimum_grade(cls, value):
        if value is None:
            return None
        if isinstance(value, str):
            stripped = value.strip()
            return stripped.upper() if stripped else None
        return value

class StrategiesReactionConfig(FrozenConfigModel):
    demand: StrategiesReactionDemandConfig = Field(default_factory=StrategiesReactionDemandConfig)
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_REACTION_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    key_level: StrategiesReactionKeyLevelConfig = Field(default_factory=StrategiesReactionKeyLevelConfig)
    liquidity_reversal: StrategiesReactionLiquidityReversalConfig = Field(default_factory=StrategiesReactionLiquidityReversalConfig)
    scale_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_REACTION_SCALE_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    session_level: StrategiesReactionSessionLevelConfig = Field(default_factory=StrategiesReactionSessionLevelConfig)
    supply: StrategiesReactionSupplyConfig = Field(default_factory=StrategiesReactionSupplyConfig)
    trendline: StrategiesReactionTrendlineConfig = Field(default_factory=StrategiesReactionTrendlineConfig)

class StrategiesScalpConfig(FrozenConfigModel):
    fade_scalp_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_FADE_SCALP_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    scalp_barrier_fallback_enabled: bool = config_field(True, canonical_env='SCALP_BARRIER_FALLBACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    scalp_barrier_fallback_min_confirmations: int = config_field(1, canonical_env='SCALP_BARRIER_FALLBACK_MIN_CONFIRMATIONS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1),), validation_summary='Pydantic required/type coercion only')
    scalp_post_impulse_range_enabled: bool = config_field(True, canonical_env='SCALP_POST_IMPULSE_RANGE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    scalp_range_provisional_enabled: bool = config_field(True, canonical_env='SCALP_RANGE_PROVISIONAL_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesMappedZoneConfig(FrozenConfigModel):
    counter_bias_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_MAP_COUNTER_BIAS_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_MAPPED_ZONE_ENABLED', deprecated_env_aliases=('AUTO_TRADE_MARKET_MAP_STRATEGY_ENABLED',), owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic type coercion + Settings cross-field model validator; EnvironmentResolver.Bool + AutoTradeOptions.Validate', evidence_notes=('Direct demo_eval resolves true while root Compose demo_eval injects false.',))

class StrategiesMatchingConfig(FrozenConfigModel):
    multiple_matches_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_MULTI_MATCH_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.EXECUTION_SAFETY, shared_with_ctrader=True, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    track_all_structural_matches: bool = config_field(False, canonical_env='AUTO_TRADE_TRACK_ALL_STRUCTURAL_MATCHES', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.EXECUTION_SAFETY, shared_with_ctrader=True, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class StrategiesRangeReversionRangeEdgeConfig(FrozenConfigModel):
    allow_rejection_only: bool = config_field(True, canonical_env='RANGE_SCALP_ALLOW_REJECTION_ONLY', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    break_closes: int = config_field(2, canonical_env='RANGE_SCALP_BREAK_CLOSES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    cluster_atr: float = config_field(0.25, canonical_env='RANGE_SCALP_CLUSTER_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only')
    cluster_min_abs: float = config_field(0.0, canonical_env='RANGE_SCALP_CLUSTER_MIN_ABS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (price).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.0),), validation_summary='Pydantic required/type coercion only')
    enabled: bool = config_field(True, canonical_env='RANGE_SCALP_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    entry_tol_atr: float = config_field(0.25, canonical_env='RANGE_SCALP_ENTRY_TOL_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only')
    lookback: int = config_field(48, canonical_env='RANGE_SCALP_LOOKBACK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 48),), validation_summary='Pydantic required/type coercion only')
    max_edge_width_atr: float = config_field(0.75, canonical_env='RANGE_SCALP_MAX_EDGE_WIDTH_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.75),), validation_summary='Pydantic required/type coercion only')
    max_width_atr: float = config_field(6.0, canonical_env='RANGE_SCALP_MAX_WIDTH_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6.0),), validation_summary='Pydantic required/type coercion only')
    min_inside_closes: int = config_field(3, canonical_env='RANGE_SCALP_MIN_INSIDE_CLOSES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only')
    min_room_atr: float = config_field(0.75, canonical_env='RANGE_SCALP_MIN_ROOM_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.75),), validation_summary='Pydantic required/type coercion only')
    min_touches: int = config_field(2, canonical_env='RANGE_SCALP_MIN_TOUCHES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    min_wick_frac: float = config_field(0.25, canonical_env='RANGE_SCALP_MIN_WICK_FRAC', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only')
    min_wick_rejections: int = config_field(1, canonical_env='RANGE_SCALP_MIN_WICK_REJECTIONS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.VERSION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1),), validation_summary='Pydantic required/type coercion only')
    min_width_atr: float = config_field(1.0, canonical_env='RANGE_SCALP_MIN_WIDTH_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),), validation_summary='Pydantic required/type coercion only')

class StrategiesRangeReversionConfig(FrozenConfigModel):
    box_scale_out_enabled: bool = config_field(True, canonical_env='AUTO_TRADE_RANGE_BOX_SCALE_OUT_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_RANGE_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, True)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    flip_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_RANGE_FLIP_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    range_edge: StrategiesRangeReversionRangeEdgeConfig = Field(default_factory=StrategiesRangeReversionRangeEdgeConfig)
    two_sided_enabled: bool = config_field(False, canonical_env='AUTO_TRADE_RANGE_TWO_SIDED_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')

class StrategiesTrendConfig(FrozenConfigModel):
    allow_chase: bool = config_field(False, canonical_env='TREND_ALLOW_CHASE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')
    atr_baseline_bars: int = config_field(48, canonical_env='TREND_ATR_BASELINE_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 48),), validation_summary='Pydantic required/type coercion only')
    atr_expansion_multiplier: float = config_field(1.15, canonical_env='TREND_ATR_EXPANSION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (multiplier).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.15),), validation_summary='Pydantic required/type coercion only')
    breakout_accept_bars: int = config_field(2, canonical_env='TREND_BREAKOUT_ACCEPT_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')
    breakout_max_age_bars: int = config_field(5, canonical_env='TREND_BREAKOUT_MAX_AGE_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (bars).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5),), validation_summary='Pydantic required/type coercion only')
    breakout_min_room_pips: int = config_field(35, canonical_env='TREND_BREAKOUT_MIN_ROOM_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (pips).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 35),), validation_summary='Pydantic required/type coercion only')
    enabled: bool = config_field(False, canonical_env='AUTO_TRADE_TREND_ENABLED', owner=ConfigOwner.SHARED, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, shared_with_ctrader=True, mismatch_policy=MismatchPolicy.WARNING, description='Controls .', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False), ContextDefault(DefaultContext.CTRADER_FROM_ENVIRONMENT, False)), validation_summary='Pydantic required/type coercion only; EnvironmentResolver.Bool + AutoTradeOptions.Validate')
    level_buffer_atr: float = config_field(1.0, canonical_env='TREND_LEVEL_BUFFER_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),), validation_summary='Pydantic required/type coercion only')
    min_height_atr: float = config_field(3.0, canonical_env='TREND_MIN_HEIGHT_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (atr).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),), validation_summary='Pydantic required/type coercion only')
    minimum_bos: int = config_field(2, canonical_env='TREND_MIN_BOS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls  (count).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only')

class StrategiesZoneDemandConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_DEMAND_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls value.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesZoneSupplyConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_SUPPLY_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Controls value.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesZoneFlipConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_FLIP_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable Flip Zone (broken key-level role flip) under the Zone family. Uses flip_zone geometry from analysis; independent of Demand/Supply Zone Reaction and Reaction-family toggles.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesZoneConfig(FrozenConfigModel):
    demand: StrategiesZoneDemandConfig = Field(default_factory=StrategiesZoneDemandConfig)
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Master enable for independent Zone (supply/demand/flip) strategies.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    flip: StrategiesZoneFlipConfig = Field(default_factory=StrategiesZoneFlipConfig)
    supply: StrategiesZoneSupplyConfig = Field(default_factory=StrategiesZoneSupplyConfig)

class StrategiesTechniqueSdConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_SD_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable Supply Demand technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueObConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_OB_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable Order Block technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueFvgConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_FVG_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable FVG technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    max_atr: float = config_field(2.0, canonical_env='AUTO_TRADE_TECHNIQUE_FVG_MAX_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Maximum FVG width in ATR.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.0),), validation_summary='Pydantic required/type coercion only')
    entry_max_width_price: float = config_field(5.0, canonical_env='AUTO_TRADE_TECHNIQUE_FVG_ENTRY_MAX_WIDTH_PRICE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Proximal entry-band width for FVG/iFVG/imbalance zones (price). Full gap kept as structural bounds; every strategy clips tradeable entry to this width.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5.0),), validation_summary='Pydantic required/type coercion only', gt=0)

class StrategiesTechniqueIfvgConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_IFVG_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable iFVG technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueCrtConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable CRT technique publisher.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    min_atr: float = config_field(1.5, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_MIN_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum H1 impulse range in ATR for CRT.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.5),), validation_summary='Pydantic required/type coercion only')
    reclaim_bars: int = config_field(6, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_RECLAIM_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Execution TF bars allowed for CRT reclaim.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 6),), validation_summary='Pydantic required/type coercion only')
    entry_max_width_price: float = config_field(5.0, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_ENTRY_MAX_WIDTH_PRICE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PRICE, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Proximal reclaim entry-band width for CRT (price). Full H1 candle kept as structural bounds; tradeable entry clips to this width (same default contract as FVG).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5.0),), validation_summary='Pydantic required/type coercion only', gt=0)
    h1_lookback_bars: int = config_field(3, canonical_env='AUTO_TRADE_TECHNIQUE_CRT_H1_LOOKBACK_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Closed H1 candles scanned for CRT impulse (forming bar excluded).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only', ge=1)

class StrategiesTechniqueConfluenceConfig(FrozenConfigModel):
    enabled: bool = config_field(True, canonical_env='AUTO_TRADE_CONFLUENCE_ZONE_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable Confluence Zone publisher when 2+ techniques overlap.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueZoneReactionFallbackConfig(FrozenConfigModel):
    enabled: bool = config_field(False, canonical_env='AUTO_TRADE_ZONE_REACTION_FALLBACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Zone Reaction fallback when technique publishers are active.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, False),), validation_summary='Pydantic required/type coercion only')

class StrategiesTechniqueConfig(FrozenConfigModel):
    sd: StrategiesTechniqueSdConfig = Field(default_factory=StrategiesTechniqueSdConfig)
    ob: StrategiesTechniqueObConfig = Field(default_factory=StrategiesTechniqueObConfig)
    fvg: StrategiesTechniqueFvgConfig = Field(default_factory=StrategiesTechniqueFvgConfig)
    ifvg: StrategiesTechniqueIfvgConfig = Field(default_factory=StrategiesTechniqueIfvgConfig)
    crt: StrategiesTechniqueCrtConfig = Field(default_factory=StrategiesTechniqueCrtConfig)
    confluence: StrategiesTechniqueConfluenceConfig = Field(default_factory=StrategiesTechniqueConfluenceConfig)
    zone_reaction_fallback: StrategiesTechniqueZoneReactionFallbackConfig = Field(default_factory=StrategiesTechniqueZoneReactionFallbackConfig)

class StrategiesScalpingArchetypesConfig(FrozenConfigModel):
    breakout_retest_enabled: bool = config_field(True, canonical_env='SCALPING_BREAKOUT_RETEST_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable micro breakout-retest scalping archetype.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    impulse_pullback_enabled: bool = config_field(True, canonical_env='SCALPING_IMPULSE_PULLBACK_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable impulse pullback continuation scalping archetype (on by default for L1 continuation).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    # Live 2026-08-28: prod +76p London / -41p Asia — hard-gate discovery + activation.
    impulse_pullback_allowed_sessions: str = config_field('london', canonical_env='SCALPING_IMPULSE_PULLBACK_ALLOWED_SESSIONS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Comma-separated UTC session names (classify_session) allowed for impulse pullback. Empty or "all" disables the gate.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'london'),), validation_summary='Pydantic required/type coercion only')
    pullback_extreme_confirm_bars: int = config_field(2, canonical_env='SCALPING_PULLBACK_EXTREME_CONFIRM_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Closed M1 bars required to confirm an impulse pullback extreme.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only', ge=1)
    impulse_displacement_atr_multiple: float = config_field(4.0, canonical_env='SCALPING_IMPULSE_DISPLACEMENT_ATR_MULTIPLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum M1 impulse displacement in M1 ATR multiples.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 4.0),), validation_summary='Pydantic required/type coercion only', ge=1, le=15)
    impulse_body_dominance: float = config_field(0.5, canonical_env='SCALPING_IMPULSE_BODY_DOMINANCE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum impulse body-to-range dominance.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    pullback_corrective_ratio: float = config_field(0.7, canonical_env='SCALPING_PULLBACK_CORRECTIVE_RATIO', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Maximum pullback body relative to impulse body.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.7),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    range_sweep_enabled: bool = config_field(True, canonical_env='SCALPING_RANGE_SWEEP_ENABLED', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Enable micro range sweep reversal scalping archetype.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')

class StrategiesScalpingContextConfig(FrozenConfigModel):
    current_context_ttl_seconds: int = config_field(3600, canonical_env='SCALPING_CURRENT_CONTEXT_TTL_SECONDS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='TTL for current immutable M5 scalp context.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3600),), validation_summary='Pydantic required/type coercion only', ge=60)
    historic_context_ttl_seconds: int = config_field(86400, canonical_env='SCALPING_HISTORIC_CONTEXT_TTL_SECONDS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='TTL for historic scalp context snapshots.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 86400),), validation_summary='Pydantic required/type coercion only', ge=3600)
    m1_lookback_bars: int = config_field(60, canonical_env='SCALPING_M1_LOOKBACK_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Bounded M1 lookback for microstructure.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 60),), validation_summary='Pydantic required/type coercion only', ge=20)
    maximum_m5_age_seconds: int = config_field(420, canonical_env='SCALPING_MAXIMUM_M5_AGE_SECONDS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.SECONDS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Fail closed when pinned M5 context is older than this.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 420),), validation_summary='Pydantic required/type coercion only', ge=60)

class StrategiesScalpingLocationConfig(FrozenConfigModel):
    # Live 2026-08-12 taxonomy: Impulse Pullback bled mid-range; tighten toward value.
    pullback_buy_maximum_position: float = config_field(0.60, canonical_env='SCALPING_PULLBACK_BUY_MAX_POSITION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Max dealing-range position for scalping pullback BUY.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.60),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    pullback_sell_minimum_position: float = config_field(0.40, canonical_env='SCALPING_PULLBACK_SELL_MIN_POSITION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Min dealing-range position for scalping pullback SELL.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.40),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    range_buy_maximum_position: float = config_field(0.35, canonical_env='SCALPING_RANGE_BUY_MAX_POSITION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Max dealing-range position for scalping range-sweep BUY.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.35),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    range_sell_minimum_position: float = config_field(0.65, canonical_env='SCALPING_RANGE_SELL_MIN_POSITION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Min dealing-range position for scalping range-sweep SELL.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.65),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    level_proximity_atr_multiple: float = config_field(1.0, canonical_env='SCALPING_LEVEL_PROXIMITY_ATR_MULTIPLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Maximum M1 ATR distance from an impulse pullback to its M5 reference.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.0),), validation_summary='Pydantic required/type coercion only', ge=0)

class StrategiesScalpingActivationConfig(FrozenConfigModel):
    # Align with execution.entry.maximum_chase_distance_pips (was 100 → late chase bleed).
    maximum_chase_pips: float = config_field(40.0, canonical_env='SCALPING_MAXIMUM_CHASE_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Miss opportunity beyond this chase distance.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 40.0),), validation_summary='Pydantic required/type coercion only', ge=0)
    maximum_chase_stop_fraction: float = config_field(0.15, canonical_env='SCALPING_MAXIMUM_CHASE_STOP_FRACTION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Chase cap as a fraction of planned stop pips; effective chase is min(maximum_chase_pips, stop_pips * fraction).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.15),), validation_summary='Pydantic required/type coercion only', ge=0)
    rearm_distance_atr: float = config_field(0.25, canonical_env='SCALPING_REARM_DISTANCE_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum distance to rearm an episode.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only', ge=0)
    trigger_maximum_age_bars: int = config_field(2, canonical_env='SCALPING_TRIGGER_MAXIMUM_AGE_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.EXECUTION_SAFETY, description='Max closed M1 bars since trigger.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only', ge=1)

class StrategiesScalpingTargetConfig(FrozenConfigModel):
    minimum_net_target_pips: float = config_field(15.0, canonical_env='SCALPING_MINIMUM_NET_TARGET_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Minimum net target after spread/slippage.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 15.0),), validation_summary='Pydantic required/type coercion only', ge=1)
    preferred_ladder_pips: str = config_field('20,25,30', canonical_env='SCALPING_PREFERRED_LADDER_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.STRING, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Comma-separated preferred scalp targets in pips.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, '20,25,30'),), validation_summary='Pydantic required/type coercion only')

class StrategiesScalpingStopConfig(FrozenConfigModel):
    buffer_atr: float = config_field(0.1, canonical_env='SCALPING_STOP_BUFFER_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.EXECUTION_SAFETY, description='ATR buffer beyond structural stop.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.1),), validation_summary='Pydantic required/type coercion only', ge=0)
    buffer_m1_atr_multiple: float = config_field(1.2, canonical_env='SCALPING_STOP_BUFFER_M1_ATR_MULTIPLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.EXECUTION_SAFETY, description='M1 ATR multiple used for the structural stop buffer.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.2),), validation_summary='Pydantic required/type coercion only', ge=0.25, le=5)
    buffer_minimum_spread_multiple: float = config_field(1.5, canonical_env='SCALPING_STOP_BUFFER_MINIMUM_SPREAD_MULTIPLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.EXECUTION_SAFETY, description='Spread-based floor multiplier for the M1 stop buffer.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.5),), validation_summary='Pydantic required/type coercion only', ge=1, le=5)
    zone_maximum_atr_multiple: float = config_field(1.5, canonical_env='SCALPING_STOP_ZONE_MAXIMUM_ATR_MULTIPLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.EXECUTION_SAFETY, description='Maximum M5 reference-zone width in M1 ATR multiples.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.5),), validation_summary='Pydantic required/type coercion only', ge=0.25, le=5)
    minimum_stop_spread_multiple: float = config_field(4.0, canonical_env='SCALPING_MINIMUM_STOP_SPREAD_MULTIPLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.EXECUTION_SAFETY, description='Reject a structural stop tighter than this multiple of the live spread; never widen structure to satisfy the cost floor.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 4.0),), validation_summary='Pydantic required/type coercion only', ge=1)
    # Dig 2026-08-25: TradePlan ignored this cap (reaction 40–60). Owner raised
    # max to 30 so Range Sweep structure room can plan without clipping too hard.
    # PR-L7 (2026-09-04) then raised the M1 buffer floor to max(m1_atr*1.2,
    # pip*spread*1.5) -- a calm-session buffer alone now runs ~8 pips and a
    # volatile one 20-30+, so 30 left little to no room for the actual
    # structural distance. Raised to 45 so the buffer widening doesn't starve
    # every archetype's stop budget (measured: stop_exceeds_maximum was the
    # single largest scalp reject reason in prod, 260 hits vs 78 for every
    # new PR-L7 semantic gate combined).
    maximum_pips: float = config_field(45.0, canonical_env='SCALPING_STOP_MAXIMUM_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Maximum scalp stop size.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 45.0),), validation_summary='Pydantic required/type coercion only', ge=1)
    minimum_pips: float = config_field(12.0, canonical_env='SCALPING_STOP_MINIMUM_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Minimum scalp stop size.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 12.0),), validation_summary='Pydantic required/type coercion only', ge=1)

class StrategiesScalpingPolicyConfig(FrozenConfigModel):
    maximum_active_opportunities: int = config_field(10, canonical_env='SCALPING_MAXIMUM_ACTIVE_OPPORTUNITIES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Cap on concurrently active scalp opportunities.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 10),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_opportunities_per_cycle: int = config_field(3, canonical_env='SCALPING_MAXIMUM_OPPORTUNITIES_PER_CYCLE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Ranked opportunities retained per M1 cycle.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_spread_pips: float = config_field(5.0, canonical_env='SCALPING_MAXIMUM_SPREAD_PIPS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PIPS, risk=RiskClassification.EXECUTION_SAFETY, description='Hard block when spread exceeds this.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5.0),), validation_summary='Pydantic required/type coercion only', ge=0)
    minimum_reward_risk: float = config_field(1.1, canonical_env='SCALPING_MINIMUM_REWARD_RISK', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.EXECUTION_SAFETY, description='Minimum net reward/risk for scalping entries.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.1),), validation_summary='Pydantic required/type coercion only', ge=0)

class StrategiesScalpingRiskConfig(FrozenConfigModel):
    cooldown_after_loss_minutes: int = config_field(5, canonical_env='SCALPING_COOLDOWN_AFTER_LOSS_MINUTES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MINUTES, risk=RiskClassification.EXECUTION_SAFETY, description='Cooldownoldown after consecutive loss streak.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5),), validation_summary='Pydantic required/type coercion only', ge=0)
    daily_loss_limit_r: float = config_field(3.0, canonical_env='SCALPING_DAILY_LOSS_LIMIT_R', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.EXECUTION_SAFETY, description='Daily realized R loss limit.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3.0),), validation_summary='Pydantic required/type coercion only', ge=0)
    maximum_concurrent_positions: int = config_field(1, canonical_env='SCALPING_MAXIMUM_CONCURRENT_POSITIONS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.EXECUTION_SAFETY, description='One XAU scalp position at a time initially.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_consecutive_losses: int = config_field(3, canonical_env='SCALPING_MAXIMUM_CONSECUTIVE_LOSSES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.EXECUTION_SAFETY, description='Loss streak before cooldown.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 3),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_daily_trades: int = config_field(30, canonical_env='SCALPING_MAXIMUM_DAILY_TRADES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.EXECUTION_SAFETY, description='Hard daily trade cap for M1 scalping.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 30),), validation_summary='Pydantic required/type coercion only', ge=1)
    maximum_session_trades: int = config_field(12, canonical_env='SCALPING_MAXIMUM_SESSION_TRADES', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.EXECUTION_SAFETY, description='Hard session trade cap for M1 scalping.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 12),), validation_summary='Pydantic required/type coercion only', ge=1)
    mode: str = config_field('live', canonical_env='SCALPING_RISK_MODE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.EXECUTION_SAFETY, description='Scalping risk accounting mode.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'live'),), allowed_values=('shadow', 'paper', 'live'), validation_summary='Pydantic type coercion + field validator', pattern='^(shadow|paper|live)$')
    risk_fraction_per_trade: float = config_field(0.1, canonical_env='SCALPING_RISK_FRACTION_PER_TRADE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.FRACTION, risk=RiskClassification.EXECUTION_SAFETY, description='Constant risk fraction — never martingale.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.1),), validation_summary='Pydantic required/type coercion only', ge=0, le=1)
    risk_percent_per_trade: float = config_field(0.5, canonical_env='SCALPING_RISK_PERCENT_PER_TRADE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.PERCENT, risk=RiskClassification.EXECUTION_SAFETY, description='Per-scalp account-risk budget in percent. Used only to size scalp TradePlans; risk_fraction_per_trade remains telemetry.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.5),), validation_summary='Pydantic required/type coercion only', ge=0.01, le=2.0)
    sizing_mode: str = config_field('equity_table', canonical_env='SCALPING_SIZING_MODE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.EXECUTION_SAFETY, description='Sizing mode for scalp TradePlans only. Non-scalp lanes retain risk.sizing.mode. equity_table sizes a scalp trade the same flat lot as any other trade (ignores risk_percent_per_trade); risk keeps the original risk-percent-of-stop-distance formula.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'equity_table'),), allowed_values=('risk', 'equity_table'), validation_summary='Pydantic type coercion + field validator', pattern='^(risk|equity_table)$')
    session_loss_limit_r: float = config_field(2.0, canonical_env='SCALPING_SESSION_LOSS_LIMIT_R', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.MULTIPLIER, risk=RiskClassification.EXECUTION_SAFETY, description='Session realized R loss limit.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2.0),), validation_summary='Pydantic required/type coercion only', ge=0)

class StrategiesScalpingBreakoutConfig(FrozenConfigModel):
    box_max_atr: float = config_field(1.5, canonical_env='SCALPING_BREAKOUT_BOX_MAX_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Max M1 compression box width in ATR for Breakout Retest.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 1.5),), validation_summary='Pydantic required/type coercion only', ge=0.1)
    max_box_bars: int = config_field(20, canonical_env='SCALPING_BREAKOUT_MAX_BOX_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Maximum M1 bars in the compression box.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 20),), validation_summary='Pydantic required/type coercion only', ge=4)
    min_box_bars: int = config_field(8, canonical_env='SCALPING_BREAKOUT_MIN_BOX_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum M1 bars in the compression box.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 8),), validation_summary='Pydantic required/type coercion only', ge=3)
    min_break_atr: float = config_field(0.25, canonical_env='SCALPING_BREAKOUT_MIN_BREAK_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum close displacement beyond the box in ATR.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.25),), validation_summary='Pydantic required/type coercion only', ge=0)
    min_touches_per_side: int = config_field(2, canonical_env='SCALPING_BREAKOUT_MIN_TOUCHES_PER_SIDE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.COUNT, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Minimum touches of each compression extreme.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 2),), validation_summary='Pydantic required/type coercion only', ge=1)
    require_retest_rejection: bool = config_field(True, canonical_env='SCALPING_BREAKOUT_REQUIRE_RETEST_REJECTION', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BOOLEAN, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Require wick/reclaim rejection on the retest (not touch-only).', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, True),), validation_summary='Pydantic required/type coercion only')
    retest_lookback_bars: int = config_field(5, canonical_env='SCALPING_BREAKOUT_RETEST_LOOKBACK_BARS', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.BARS, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Bars to scan for rejection retest after an accepted break.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 5),), validation_summary='Pydantic required/type coercion only', ge=1)
    touch_tol_atr: float = config_field(0.2, canonical_env='SCALPING_BREAKOUT_TOUCH_TOL_ATR', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ATR, risk=RiskClassification.STRATEGY_BEHAVIOR, description='Touch band around box extremes in ATR.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 0.2),), validation_summary='Pydantic required/type coercion only', ge=0)

class StrategiesScalpingConfig(FrozenConfigModel):
    activation: StrategiesScalpingActivationConfig = Field(default_factory=StrategiesScalpingActivationConfig)
    archetypes: StrategiesScalpingArchetypesConfig = Field(default_factory=StrategiesScalpingArchetypesConfig)
    breakout: StrategiesScalpingBreakoutConfig = Field(default_factory=StrategiesScalpingBreakoutConfig)
    context: StrategiesScalpingContextConfig = Field(default_factory=StrategiesScalpingContextConfig)
    location: StrategiesScalpingLocationConfig = Field(default_factory=StrategiesScalpingLocationConfig)
    mode: str = config_field('live', canonical_env='SCALPING_MODE', owner=ConfigOwner.PYTHON, reload=ReloadPolicy.NEW_SETUP_ONLY, runtime_reload=ReloadPolicy.RESTART, unit=ConfigUnit.ENUM, risk=RiskClassification.EXECUTION_SAFETY, description='Scalping runtime mode: off, shadow, paper, or live.', default_contexts=(ContextDefault(DefaultContext.PYTHON_SCHEMA, 'live'),), allowed_values=('off', 'shadow', 'paper', 'live'), validation_summary='Pydantic type coercion + field validator', pattern='^(off|shadow|paper|live)$')
    policy: StrategiesScalpingPolicyConfig = Field(default_factory=StrategiesScalpingPolicyConfig)
    risk: StrategiesScalpingRiskConfig = Field(default_factory=StrategiesScalpingRiskConfig)
    stop: StrategiesScalpingStopConfig = Field(default_factory=StrategiesScalpingStopConfig)
    target: StrategiesScalpingTargetConfig = Field(default_factory=StrategiesScalpingTargetConfig)

class StrategiesConfig(FrozenConfigModel):
    auto_scalp: StrategiesAutoScalpConfig = Field(default_factory=StrategiesAutoScalpConfig)
    breakout: StrategiesBreakoutConfig = Field(default_factory=StrategiesBreakoutConfig)
    counter_trend: StrategiesCounterTrendConfig = Field(default_factory=StrategiesCounterTrendConfig)
    scalping: StrategiesScalpingConfig = Field(
      default_factory=StrategiesScalpingConfig,
    )
    mapped_zone: StrategiesMappedZoneConfig = Field(default_factory=StrategiesMappedZoneConfig)
    matching: StrategiesMatchingConfig = Field(default_factory=StrategiesMatchingConfig)
    range_reversion: StrategiesRangeReversionConfig = Field(default_factory=StrategiesRangeReversionConfig)
    reaction: StrategiesReactionConfig = Field(default_factory=StrategiesReactionConfig)
    scalp: StrategiesScalpConfig = Field(default_factory=StrategiesScalpConfig)
    selection: StrategiesSelectionConfig = Field(default_factory=StrategiesSelectionConfig)
    trend: StrategiesTrendConfig = Field(default_factory=StrategiesTrendConfig)
    technique: StrategiesTechniqueConfig = Field(default_factory=StrategiesTechniqueConfig)
    zone: StrategiesZoneConfig = Field(default_factory=StrategiesZoneConfig)
