package detectorparity_test

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/config"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/engine"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/market"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/opportunity"
	"github.com/st-mich43l/apexvoid-trading-bot/analysis-engine/internal/replaycapture"
)

// The golden is the decision of every frozen Python detector over the same
// committed closed-bar captures, generated by generate_oracle_golden.py. These
// tests replay the captures through the Go engine and compare every closed bar:
// no detector may emit where the oracle did not, none may stay silent where it
// did, and each decision must agree on direction, entry band, confluence stars
// and the touch/confirmation bars. The golden is never produced by Go.

var covered = []string{"break_retest", "range_edge", "snap_back", "momentum_ride", "fade_scalp"}

type goldenDetector struct {
	Direction       string  `json:"direction"`
	EntryLow        float64 `json:"entry_low"`
	EntryHigh       float64 `json:"entry_high"`
	Confluence      int     `json:"confluence"`
	TouchBar        *int64  `json:"touch_bar"`
	ConfirmationBar *int64  `json:"confirmation_bar"`
	StructuralKind  *string `json:"structural_kind"`
}

type goldenBar struct {
	Bar       int64                     `json:"bar"`
	HTFBias   string                    `json:"htf_bias"`
	LocalBias string                    `json:"local_bias"`
	Regime    string                    `json:"regime"`
	PDZone    *string                   `json:"pd_zone"`
	Detectors map[string]goldenDetector `json:"detectors"`
}

type goldenSymbol struct {
	Capture string      `json:"capture"`
	Bars    []goldenBar `json:"bars"`
}

type golden struct {
	OracleCommit string                  `json:"oracle_commit"`
	Symbols      map[string]goldenSymbol `json:"symbols"`
}

type observedBar struct {
	localBias, htfBias, regime string
	pdZone                     *string
	candidates                 map[string][]opportunity.Candidate
}

func loadGolden(t *testing.T) golden {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("..", "..", "testdata", "detector-parity-oracle.json"))
	if err != nil {
		t.Fatal(err)
	}
	var g golden
	if err := json.Unmarshal(data, &g); err != nil {
		t.Fatal(err)
	}
	return g
}

func replay(t *testing.T, doc *config.Document, file string) (market.Symbol, map[int64]*observedBar) {
	t.Helper()
	capture, err := replaycapture.Load(filepath.Join("..", "..", "testdata", file))
	if err != nil {
		t.Fatal(err)
	}
	observed := map[int64]*observedBar{}
	_, err = replaycapture.Replay(doc, capture, market.M5, replaycapture.Options{OnEvaluation: func(e engine.Evaluation) {
		if e.Timeframe != market.M5 || e.Context == nil || e.Context.Legacy == nil {
			return
		}
		frame := e.Context.Timeframes[market.M5].Legacy
		if frame == nil {
			return
		}
		bar := &observedBar{localBias: e.Context.Legacy.LocalStructure, htfBias: e.Context.Legacy.HTFBias, regime: frame.Regime.Kind, candidates: map[string][]opportunity.Candidate{}}
		if frame.Range != nil {
			zone := frame.Range.Zone
			bar.pdZone = &zone
		}
		for _, candidate := range e.Candidates {
			bar.candidates[string(candidate.Strategy)] = append(bar.candidates[string(candidate.Strategy)], candidate)
		}
		observed[e.BarTime] = bar
	}})
	if err != nil {
		t.Fatal(err)
	}
	return capture.Symbol, observed
}

// outwardTick is the engine's price normalisation of an entry band: the low is
// floored and the high ceiled onto the instrument's tick grid. The oracle's
// band is exact, so it is compared after the same normalisation.
func outwardTick(low, high float64, digits int) (float64, float64) {
	tick := math.Pow10(-digits)
	return math.Floor(low/tick+1e-6) * tick, math.Ceil(high/tick-1e-6) * tick
}

func compareDetector(symbol string, digits int, bar goldenBar, name string, want goldenDetector, got []opportunity.Candidate, mismatches *[]string) {
	fail := func(format string, args ...any) {
		*mismatches = append(*mismatches, fmt.Sprintf("%s %s bar %d: %s", symbol, name, bar.Bar, fmt.Sprintf(format, args...)))
	}
	var match *opportunity.Candidate
	for i := range got {
		if string(got[i].Direction) == want.Direction {
			match = &got[i]
			break
		}
	}
	if match == nil {
		fail("oracle %s but Go direction(s) %v", want.Direction, directions(got))
		return
	}
	low, high := outwardTick(want.EntryLow, want.EntryHigh, digits)
	tolerance := math.Pow10(-digits) * .01
	if math.Abs(float64(match.Entry.Low)-low) > tolerance || math.Abs(float64(match.Entry.High)-high) > tolerance {
		fail("entry %.6f-%.6f, oracle %.6f-%.6f (normalised %.6f-%.6f)", match.Entry.Low, match.Entry.High, want.EntryLow, want.EntryHigh, low, high)
	}
	if match.Technical == nil || match.Technical.Confluence == nil || match.Technical.Confluence.SelectedStars != want.Confluence {
		stars := -1
		if match.Technical != nil && match.Technical.Confluence != nil {
			stars = match.Technical.Confluence.SelectedStars
		}
		fail("confluence %d, oracle %d", stars, want.Confluence)
	}
	if want.TouchBar != nil || want.ConfirmationBar != nil {
		if match.Reaction == nil {
			fail("oracle has a confirmation, Go has no reaction")
			return
		}
		if want.TouchBar != nil && match.Reaction.TouchBarTime != *want.TouchBar {
			fail("touch bar %d, oracle %d", match.Reaction.TouchBarTime, *want.TouchBar)
		}
		if want.ConfirmationBar != nil && match.Reaction.ConfirmationBarTime != *want.ConfirmationBar {
			fail("confirmation bar %d, oracle %d", match.Reaction.ConfirmationBarTime, *want.ConfirmationBar)
		}
	}
}

func directions(candidates []opportunity.Candidate) []string {
	var out []string
	for _, c := range candidates {
		out = append(out, string(c.Direction))
	}
	return out
}

func TestGoDetectorsMatchTheFrozenPythonOracleBarByBar(t *testing.T) {
	g := loadGolden(t)
	if g.OracleCommit != "1c9f32303b7e9f15fc8e3767b5045ac1e8a37adc" {
		t.Fatalf("golden was not generated from the frozen oracle: %q", g.OracleCommit)
	}
	doc, err := config.ResolveDocument(filepath.Join("..", "..", "..", "config", "apexvoid.yml"))
	if err != nil {
		t.Fatal(err)
	}
	var symbols []string
	for symbol := range g.Symbols {
		symbols = append(symbols, symbol)
	}
	sort.Strings(symbols)
	compared := map[string]int{}
	for _, symbol := range symbols {
		data := g.Symbols[symbol]
		geometry, err := doc.GeometryFor(symbol)
		if err != nil {
			t.Fatal(err)
		}
		_, observed := replay(t, doc, data.Capture)
		var mismatches []string
		for _, bar := range data.Bars {
			got, ok := observed[bar.Bar]
			if !ok {
				mismatches = append(mismatches, fmt.Sprintf("%s bar %d was never evaluated by Go", symbol, bar.Bar))
				continue
			}
			if got.localBias != bar.LocalBias || got.htfBias != bar.HTFBias || got.regime != bar.Regime {
				mismatches = append(mismatches, fmt.Sprintf("%s bar %d facts: local %s/%s htf %s/%s regime %s/%s (go/oracle)", symbol, bar.Bar, got.localBias, bar.LocalBias, got.htfBias, bar.HTFBias, got.regime, bar.Regime))
			}
			if (got.pdZone == nil) != (bar.PDZone == nil) || got.pdZone != nil && *got.pdZone != *bar.PDZone {
				mismatches = append(mismatches, fmt.Sprintf("%s bar %d premium/discount zone differs", symbol, bar.Bar))
			}
			for _, name := range covered {
				want, expected := bar.Detectors[name]
				emitted := got.candidates[name]
				switch {
				case expected && len(emitted) == 0:
					mismatches = append(mismatches, fmt.Sprintf("%s %s bar %d: oracle emitted %s, Go did not", symbol, name, bar.Bar, want.Direction))
				case !expected && len(emitted) > 0:
					mismatches = append(mismatches, fmt.Sprintf("%s %s bar %d: Go emitted %v, oracle did not", symbol, name, bar.Bar, directions(emitted)))
				case expected:
					compared[name]++
					compareDetector(symbol, geometry.PriceDigits, bar, name, want, emitted, &mismatches)
				}
			}
		}
		for i, m := range mismatches {
			if i == 15 {
				t.Errorf("%s: ... and %d more", symbol, len(mismatches)-15)
				break
			}
			t.Error(m)
		}
	}
	// The comparison is only meaningful if the oracle actually decided
	// something for each detector on these captures.
	for _, name := range covered {
		if compared[name] == 0 {
			t.Errorf("the golden holds no %s decision to compare", name)
		}
	}
}
