-- schema.sql — reference DDL for the apexvoid-trading-bot PostgreSQL database.
--
-- Authoritative creator: algo-bot/app/persistence/store.py::init_db()
-- (idempotent IF NOT EXISTS + ALTER migrations on every boot).
-- Keep this file aligned when adding tables; do not treat it as a migrator.

-- Append-only log of pips results auto-edited into the channel.
CREATE TABLE IF NOT EXISTS pips_log (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts         BIGINT  NOT NULL,
  sign       TEXT    NOT NULL,
  pips       INTEGER NOT NULL,
  message_id BIGINT,
  chat_id    TEXT,
  signal_id  BIGINT
);
CREATE INDEX IF NOT EXISTS idx_pips_ts        ON pips_log(ts);
CREATE INDEX IF NOT EXISTS idx_pips_signal_id ON pips_log(signal_id);

-- Lifecycle tracker for every signal posted via the bot's DM interface.
CREATE TABLE IF NOT EXISTS manual_signals (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts                   BIGINT           NOT NULL,
  action               TEXT             NOT NULL,
  entry                DOUBLE PRECISION NOT NULL,
  entry_end            DOUBLE PRECISION,
  sl                   DOUBLE PRECISION NOT NULL,
  original_sl          DOUBLE PRECISION,
  tps                  TEXT             NOT NULL,
  order_type           TEXT             NOT NULL,
  channel_message_id   BIGINT,
  status               TEXT             NOT NULL DEFAULT 'open',
  result_pips          INTEGER,
  closed_at            BIGINT,
  daily_seq            INTEGER,
  trade_date           TEXT,
  fill_state           TEXT             NOT NULL DEFAULT 'pending',
  filled_at            BIGINT,
  legs                 TEXT             NOT NULL DEFAULT '[]',
  parent_id            BIGINT,
  setup_type           TEXT,
  confluence           INTEGER,
  note                 TEXT,
  symbol               TEXT             NOT NULL DEFAULT 'XAU',
  visibility           TEXT             NOT NULL DEFAULT 'both',
  algo_armed           BOOLEAN          NOT NULL DEFAULT FALSE,
  trade_stream         TEXT             NOT NULL DEFAULT 'manual',
  execution_mode       TEXT             NOT NULL DEFAULT 'notify',
  execution_status     TEXT,
  execution_intent_id  TEXT,
  execution_revision   INTEGER          NOT NULL DEFAULT 0,
  broker_position_id   TEXT,
  broker_fill_price    DOUBLE PRECISION,
  execution_error      TEXT
);
CREATE INDEX IF NOT EXISTS idx_manual_signals_status
  ON manual_signals(status);
CREATE INDEX IF NOT EXISTS idx_manual_signals_trade_date
  ON manual_signals(trade_date);
CREATE INDEX IF NOT EXISTS idx_manual_signals_symbol_trade_date
  ON manual_signals(symbol, trade_date);
CREATE INDEX IF NOT EXISTS idx_manual_signals_parent_id
  ON manual_signals(parent_id);

-- Broker fill ledger (scale-ins keep separate rows).
CREATE TABLE IF NOT EXISTS auto_trade_fills (
  position_id       BIGINT PRIMARY KEY,
  group_id          TEXT             NOT NULL,
  trade_key         TEXT             NOT NULL,
  trade_stream      TEXT             NOT NULL,
  symbol            TEXT             NOT NULL DEFAULT 'XAU',
  setup_type        TEXT,
  direction         TEXT,
  entry_price       DOUBLE PRECISION,
  stop_pips         DOUBLE PRECISION,
  volume            BIGINT,
  filled_at         BIGINT           NOT NULL,
  correction_source TEXT,
  corrected_at      BIGINT
);
CREATE INDEX IF NOT EXISTS idx_auto_trade_fills_group
  ON auto_trade_fills(group_id);

-- One closed result per execution group.
CREATE TABLE IF NOT EXISTS auto_trade_results (
  group_id          TEXT PRIMARY KEY,
  trade_key         TEXT             NOT NULL,
  trade_stream      TEXT             NOT NULL,
  result_pips       DOUBLE PRECISION NOT NULL,
  closed_at         BIGINT           NOT NULL,
  setup_type        TEXT,
  direction         TEXT,
  session           TEXT,
  killzone_name     TEXT,
  stop_pips         DOUBLE PRECISION,
  booked_tp_count   INTEGER,
  utc_hour          INTEGER,
  symbol            TEXT             NOT NULL DEFAULT 'XAU',
  correction_source TEXT,
  corrected_at      BIGINT
);
CREATE INDEX IF NOT EXISTS idx_auto_trade_results_closed
  ON auto_trade_results(closed_at);

-- One row per delivered post (VIP / public) for a signal.
CREATE TABLE IF NOT EXISTS signal_posts (
  signal_id  BIGINT NOT NULL,
  channel_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL,
  tier       TEXT   NOT NULL,
  PRIMARY KEY (signal_id, channel_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_signal_posts_message
  ON signal_posts(channel_id, message_id);

-- Economic calendar events cached from ForexFactory feeds.
CREATE TABLE IF NOT EXISTS events (
  event_id  TEXT    PRIMARY KEY,
  ts_utc    BIGINT  NOT NULL,
  currency  TEXT    NOT NULL,
  title     TEXT    NOT NULL,
  impact    TEXT    NOT NULL,
  forecast  TEXT,
  previous  TEXT,
  actual    TEXT,
  all_day   INTEGER NOT NULL DEFAULT 0,
  source    TEXT    NOT NULL DEFAULT 'ff',
  synced_at BIGINT  NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts_utc);

-- Small key/value store (e.g. last calendar digest date).
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);
