-- schema.sql — reference DDL for the apexvoid-trading-bot PostgreSQL database.
--
-- This mirrors app/dedup.py::init_db(), which is the authoritative schema
-- creator run automatically on startup. This file is provided for manual
-- provisioning and documentation; keep it in sync with init_db() if that
-- changes. All statements are idempotent.

-- Append-only log of pips results auto-edited into the channel.
CREATE TABLE IF NOT EXISTS pips_log (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts         BIGINT  NOT NULL,   -- unix timestamp of the edit
  sign       TEXT    NOT NULL,   -- '+' for profit, '-' for loss
  pips       INTEGER NOT NULL,   -- absolute pip count (always positive)
  message_id BIGINT,             -- Telegram message_id that was edited
  chat_id    TEXT,               -- Telegram chat_id of the channel
  signal_id  BIGINT              -- linked manual_signals row, if any
);
CREATE INDEX IF NOT EXISTS idx_pips_ts        ON pips_log(ts);
CREATE INDEX IF NOT EXISTS idx_pips_signal_id ON pips_log(signal_id);

-- Lifecycle tracker for every signal posted via the bot's DM interface.
CREATE TABLE IF NOT EXISTS manual_signals (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts                 BIGINT           NOT NULL,
  action             TEXT             NOT NULL,       -- 'BUY' or 'SELL'
  entry              DOUBLE PRECISION NOT NULL,
  entry_end          DOUBLE PRECISION,
  sl                 DOUBLE PRECISION NOT NULL,
  tps                TEXT             NOT NULL,       -- JSON array of TP prices
  order_type         TEXT             NOT NULL,
  channel_message_id BIGINT,
  status             TEXT             NOT NULL DEFAULT 'open',
  result_pips        INTEGER,
  closed_at          BIGINT,
  daily_seq          INTEGER,
  trade_date         TEXT,
  fill_state         TEXT             NOT NULL DEFAULT 'pending',
  filled_at          BIGINT,
  legs               TEXT             NOT NULL DEFAULT '[]',  -- JSON array
  parent_id          BIGINT,
  setup_type         TEXT,
  confluence         INTEGER,
  note               TEXT,
  symbol             TEXT             NOT NULL DEFAULT 'XAU',
  visibility         TEXT             NOT NULL DEFAULT 'both'
);
CREATE INDEX IF NOT EXISTS idx_manual_signals_status
  ON manual_signals(status);
CREATE INDEX IF NOT EXISTS idx_manual_signals_trade_date
  ON manual_signals(trade_date);
CREATE INDEX IF NOT EXISTS idx_manual_signals_symbol_trade_date
  ON manual_signals(symbol, trade_date);
CREATE INDEX IF NOT EXISTS idx_manual_signals_parent_id
  ON manual_signals(parent_id);

-- One row per delivered post (VIP / public) for a signal.
CREATE TABLE IF NOT EXISTS signal_posts (
  signal_id  BIGINT NOT NULL,
  channel_id BIGINT NOT NULL,
  message_id BIGINT NOT NULL,
  tier       TEXT   NOT NULL,
  PRIMARY KEY (signal_id, channel_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_signal_posts_message
  ON signal_posts(channel_id, message_id);

-- Economic calendar events cached from ForexFactory feeds.
CREATE TABLE IF NOT EXISTS events (
  event_id  TEXT    PRIMARY KEY,
  ts_utc    BIGINT  NOT NULL,
  currency  TEXT    NOT NULL,
  title     TEXT    NOT NULL,
  impact    TEXT    NOT NULL,
  forecast  TEXT,
  previous  TEXT,
  actual    TEXT,
  all_day   INTEGER NOT NULL DEFAULT 0,
  source    TEXT    NOT NULL DEFAULT 'ff',
  synced_at BIGINT  NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_ts ON events(ts_utc);

-- Small key/value store (e.g. last calendar digest date).
CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT
);
